### ISSUE TITLE
Display EAN13 flat on the bottom (like EAN8)

### ISSUE THREAD

**Issue by slolo2000** [lindell/JsBarcode#102]
It would be nice to have the possibility to display an EAN13 codebar in rectangular form (flat on the bottom) like EAN8.
Like that, we should be able to copy/past the ean13 text without spaces and mostly choose the size font.

**Comment by lindell** [comment]
[JsBarcode v3.5.0-beta.2](https://github.com/lindell/JsBarcode/releases/tag/v3.5.0-beta.2) contains option `flat` for EAN-13. Please test and confirm this works as you intended.

````javascript
JsBarcode("#barcode", "590123412345", {
  format: "EAN13",
  flat: true
});
````
![Flat](http://i.imgur.com/C5j7Hgb.png)

**Comment by slolo2000** [comment]
Hi,


I have done a test with the last beta version and it works very well!

I am also able to change font size so it is perfect like that.


Thank you very much for your great work.

________________________________
De : Johan Lindell <notifications@github.com>
Envoyé : dimanche 25 septembre 2016 19:46:34
À : lindell/JsBarcode
Cc : slolo2000; Author
Objet : Re: [lindell/JsBarcode] Display EAN13 flat on the bottom (like EAN8) (#102)


JsBarcode v3.5.0-beta.2<https://github.com/lindell/JsBarcode/releases/tag/v3.5.0-beta.2> contains option flat for EAN-13. Please test and confirm this works as you intended.

JsBarcode("#barcode", "590123412345", {
  format: "EAN13",
  flat: true
});

[Flat]<https://camo.githubusercontent.com/7b3ca34823eb182cd80cc89c82a9d4bcafb4b604/687474703a2f2f692e696d6775722e636f6d2f43356a374867622e706e67>

-
