### ISSUE TITLE
Typings file for TypeScript & Angular 2

### ISSUE THREAD

**Issue by maddy2get** [lindell/JsBarcode#105]
Hey there,

I was trying to use this lib on an angular 2 project and just wondering if you would be able to add in typings definitions for this lib? Please see this link for more info: https://github.com/typings/typings/issues/322

Thanks in advance.

**Comment by lindell** [comment]
Sounds like a great initiative. I would gladly accept a pull request 😄

**Comment by CooleyGit** [comment]
+1 Would be nice to have a typings definitions. 

I am currently using this plugin in an Ionic 2 app but I had to create a `declarations.d.ts` file with `declare module 'jsbarcode';` "All this does is tell the Typescript compiler that the module is found, and it is an object of any type. This will allow the library to be used freely without the Typescript compiler giving errors." [From ionic 2 docs](http://ionicframework.com/docs/v2/resources/third-party-libs/)

Basic example below:
```
import { Component, ViewChild, ElementRef } from '@angular/core';
import JsBarcode from 'jsbarcode';

@Component({
 template: `
     <svg #barcode id="barcode"></svg>`
`})
export class BarcodeEx {
    @ViewChild('barcode') barcode: ElementRef;
    ngAfterViewInit() {
       JsBarcode(this.barcode.nativeElement, '12345');
    }
}
```

**Comment by lindell** [comment]
Added it myself now. Could you confirm everything seems like you expected @maddy2get by installing it via.

````
npm install https://github.com/lindell/JsBarcode
````

**Comment by CooleyGit** [comment]
I just reinstalled on my app works great. Thanks

**Comment by fahmisaad** [comment]
Can someone teach me on how to convert it to image in ionic. kinda stuck here
