### ISSUE TITLE
Chrome Error: JsBarcode.all.min.js:1 Uncaught Error: Not supported type to render on.

### ISSUE THREAD

**Issue by Avinashachu007** [lindell/JsBarcode#109]
While Loading page console shows "JsBarcode.all.min.js:1 Uncaught Error: Not supported type to render on." and no Barcode is generated

**Comment by lindell** [comment]
Please provide a way to reproduce this.

**Comment by lindell** [comment]
Hi.

Thanks for creating an issue. Unfortunately there is no way to diagnose this issue if you can't provide a way to reproduce it. This could be done by creating a [Codepen](http://codepen.io/pen/), a [jsfiddle](https://jsfiddle.net/), upload a zip-file with all nessecary files or by linking to a live version where the problem occur.

**Comment by Avinashachu007** [comment]
@lindell  Thanks For Replying.  This error is Rectified!. I have done a small error in my code. **There is nothing wrong in ur Library**. what I have done is used Same ID on two divs. Thatswhy the above error.
Thanks a lot :+1:

**Comment by mdjaman** [comment]
Have the same issue!
Unfortunately could resolve it!

Here the fiddle [jsfiddle.net/mdjaman/5twr7479/](url)
