### ISSUE TITLE
Override Display Text in Chinese character

### ISSUE THREAD

**Issue by bakbluelabel** [lindell/JsBarcode#110]
Hi lindell, thanks for such a wonderful barcode generator. I'm trying to use the default Code128 with img tag and override the display text with some extra description in Chinese characters, however, the Chinese character display as empty. Would it possible to display Chinese or other character using the "text" parameter?

Thanks.

**Comment by lindell** [comment]
Hi.

This seems to be an issue with code128 removing characters that is not supported by the encoding itself. I will take a look at this.

**Comment by lindell** [comment]
Fixed the bug and released a patch in the form of [v3.5.4](https://github.com/lindell/JsBarcode/releases/tag/v3.5.4)

**Comment by lindell** [comment]
http://codepen.io/lindell/pen/YGJYLa

**Comment by bakbluelabel** [comment]
ha ha ha.... Thank you very much!
