### ISSUE TITLE
"Uncaught ReferenceError: exports is not defined" after minifying app

### ISSUE THREAD

**Issue by ivanwitzke** [lindell/JsBarcode#111]
Hello.
I used your library in an angular app and after I minifyed the app using grunt the app doesn't starts.
Any clue of what happened or what I can do to fix it?

![jsbarcodeerror](https://cloud.githubusercontent.com/assets/4406761/19767488/d9514ec6-9c31-11e6-969b-021104335fd6.png)

**Comment by lindell** [comment]
This seems to be an error with the compilation since that line does not exist in `src/` and is generated by babel. What is the error you get? How do you call Jsbarcode to reproduce this? What is the callstack? Could you provide any way of reproduce the error?

**Comment by ivanwitzke** [comment]
After some research, it looks like it's related to the browser support for commonJS... so I guess the problem it's not on the library itself...

**Comment by lindell** [comment]
Good to know 😄 If you haven't solved the problem yet it you could probably solve the problem by compiling [require.js](http://requirejs.org/) into your project
