### ISSUE TITLE
Setting barcode height fails if set from a string value

### ISSUE THREAD

**Issue by swegen** [lindell/JsBarcode#113]
[jsbin example](http://jsbin.com/tiloxafawa/edit?html,output)
This library should use `parseInt()` internally to be more robust.

**Comment by lindell** [comment]
Pushed [JsBarcode v3.5.4](https://github.com/lindell/JsBarcode/releases/tag/v3.5.4) to deal with this.

**Comment by lindell** [comment]
http://jsbin.com/zifexozacu/edit?html,output

**Comment by swegen** [comment]
Fast fix! Thank you for this nice project.
