### ISSUE TITLE
Background color doesn't print in some browsers

### ISSUE THREAD

**Issue by sammie-p** [lindell/JsBarcode#115]
Setting the background color seems to set the generated SVG's CSS style to a specific background color, but CSS backgrounds do not print by default in a lot of browsers. Can a rect element be created instead with a fill of the specified background color?

**Comment by lindell** [comment]
If this is the case I will absolutely change it. Could you please list some browsers where this is the case?

**Comment by sammie-p** [comment]
I can confirm this is an issue with the latest Firefox, Chrome and Edge on Windows 10. It can be fixed in Chrome (and presumably Safari) with the -webkit-print-color-adjust:exact style, which will print everything as it appears on screen.

Attached are some screenshots of this behaviour.
![edge screencap](https://cloud.githubusercontent.com/assets/19430483/20610580/bd709aac-b2ef-11e6-85b1-d11aaecd3928.png)
![Uploading firefox printout.png…]()
![chrome screencap](https://cloud.githubusercontent.com/assets/19430483/20610581/bd77cf84-b2ef-11e6-93f1-e2dbfaa0de68.png)

**Comment by lindell** [comment]
Oh, when you wrote "print" you meant actually printing it to paper (not printing (drawing) to screen). I can see the same problem and will fix it tomorrow.

**Comment by lindell** [comment]
Release [v3.5.6](https://github.com/lindell/JsBarcode/releases/tag/v3.5.6) should fix the problem.

**Comment by sammie-p** [comment]
Thanks Lindell, it's a great project!
