### ISSUE TITLE
valid not called when using init

### ISSUE THREAD

**Issue by brianchance** [lindell/JsBarcode#118]
When an invalid EAN is passed, the valid function is called when passing the options directly, but is not called when using `.init()`, it just throws an InvalidInputException that is not caught using the ErrorHandler.

HTML
```html
<svg id="barcode1"></svg>
<svg id="barcode2"
      jsbarcode-format="ean13"
      jsbarcode-value="0843788027640">
</svg>
```

Javascript
```javascript
JsBarcode("#barcode1", "0843788027640", {
  format: "ean13",
  valid: function(v) {
    console.log(v);
  }
});
JsBarcode('#barcode2')
  .options({ valid: function(v) { console.log(v); } })
  .init();
```

**Comment by lindell** [comment]
Will take a look at this.

**Comment by lindell** [comment]
[JsBarcode v3.5.7](https://github.com/lindell/JsBarcode/releases/tag/v3.5.7) should fix this issue.
Could you please confirm this.

**Comment by brianchance** [comment]
Works, thank you for the amazing turnaround.
