### ISSUE TITLE
Text not work with release v3.5.6

### ISSUE THREAD

**Issue by cesarmm** [lindell/JsBarcode#119]
Hi,
 I'd tried the example with current release v3.5.6 and not works. Show "Hello".
```
JsBarcode("#barcode", "Hello", {
  text: "Hi!"
});
```
With release v3.5.1 it works. Show "Hi!".

**Comment by lindell** [comment]
Tried it on codepen. Still works on 3.5.6 http://codepen.io/lindell/pen/jVJdqP

**Comment by cesarmm** [comment]
I see the problem. The release in http://lindell.me/JsBarcode/#download is v3.3.7.

Sorry!

**Comment by lindell** [comment]
Oh, this need to be updated automatically. Will have this fixed. Sorry for the inconvenience.

**Comment by cesarmm** [comment]
Thank you for your speed.
