### ISSUE TITLE
ITF-14 checksum

### ISSUE THREAD

**Issue by mamisoa** [lindell/JsBarcode#120]
Hi,
Would it be possible to set an option to remove the checksum check and autocomplete in ITF-14?
I would need to generate ITF-14 code e.g "189506310010" that do not strictly conforms to the norm, but is widely use in medical prescription in Belgium.

Thanks.

**Comment by lindell** [comment]
Just use the ITF barcode. It encodes in the same way as ITF-14 but does not enforce 14 digits or any checksum.

**Comment by mamisoa** [comment]
Thanks. So easy. Sorry.

**Comment by lindell** [comment]
No problem. Good luck with what you are building 😄
