### ISSUE TITLE
how can I display text in lines

### ISSUE THREAD

**Issue by hiwanz** [lindell/JsBarcode#121]
What I want is something like below:
```
||||||||||||||||||
9780199532179 
The meaning of life
```
I've try option text:'9780199532179\nThe meaning of life' but not worked

**Comment by lindell** [comment]
Multi line text is not supported and I will most likely not put time into adding it.

I would recommend to add it below the barcode in a parent div [Like this](http://codepen.io/lindell/pen/MJKLwY)

**Comment by hiwanz** [comment]
@lindell,I know how to make it look like that,but that's not my point,I want to print them on label papers,anyway I've fixed this the other way,thank you all the time
