### ISSUE TITLE
List of formats to pass to options

### ISSUE THREAD

**Issue by bryantmakesprog** [lindell/JsBarcode#123]
Could we get a list of values you can pass to the format option parameter? I see the ones in the examples, but this doesn't strike me as a comprehensive list of accepted values.

**Comment by lindell** [comment]
Try to scroll down a bit further to https://github.com/lindell/JsBarcode#Options

**Comment by bryantmakesprog** [comment]
Just to verify, I can put in any of the following values?

- CODE128
- EAN
- UPC
- CODE39
- ITF-14
- MSI
- Pharmacode
- Codabar

Does casing matter? I am currently passing in `upc` and it functions, but will this be the case for any of the options above?

**Comment by lindell** [comment]
All barcodes should work with both lower and upper case.

**Comment by bryantmakesprog** [comment]
My apologies, just realized you have a very robust wiki. Definitely an under-used feature, really appreciate the documentation :1st_place_medal:
