### ISSUE TITLE
Wrong width calculation for barcodes without text

### ISSUE THREAD

**Issue by citylifeprison** [lindell/JsBarcode#124]
No check for `displayValue: false` in `calculateEncodingAttributes` resulting in wrong width calculation for barcodes with hidden text and width: 1.

**Comment by lindell** [comment]
Could you please provide an example on jsfiddle, codepen or similairly

**Comment by lindell** [comment]
Ah, this might occur if fontSize is set very high while still setting `displayValue: false`.
I will fix this soon, thanks for the report.

**Comment by citylifeprison** [comment]
Here is jsfiddle: [https://jsfiddle.net/7uh2a92v/1/](https://jsfiddle.net/7uh2a92v/1/)
As you can see, there is two barcodes generated, one with `displayValue` set to `false` and other to `true`.
Both have same width, though first one should be only 95 pixels, thats because of this line in `calculateEncodingAttributes`:
`encoding.width = Math.ceil(Math.max(textWidth, barcodeWidth));`.
Width of text is taken into account, even if text is hidden.

**Comment by lindell** [comment]
[JsBarcode v3.5.8](https://github.com/lindell/JsBarcode/releases/tag/v3.5.8) should fix the problem.
