### ISSUE TITLE
Feature Request: Generate QR Code

### ISSUE THREAD

**Issue by aljibbs** [lindell/JsBarcode#125]
Will you ever include QR Code generation or any two-dimensional barcode type?

**Comment by lindell** [comment]
Sorry, I will not. If I do every program a QR Code Generator it will not be included in JsBarcode. But there are already a lot of great QR code generators on GitHub. Check out https://github.com/davidshimjs/qrcodejs for example.

**Comment by aljibbs** [comment]
Thanks
