### ISSUE TITLE
NoElementException: No element to render on.

### ISSUE THREAD

**Issue by pankaja92** [lindell/JsBarcode#127]
Hello,

For a project, I started using JsBarcode with Angularjs. Here I need to create the number of barcodes according to the user inputs. I'm using the ng-repeat directive to populate them.

<table ng-model="barcodeTable" ng-style="{width : valueOftbl}">
                <tr ng-repeat="row in arrayList">
                    <td ng-repeat="item in row">
                        <img id="code128" />
                    </td>
                </tr>
            </table>

The table is created with a button click event. Here the table works fine. But the barcode is not generated. I'm getting the error "NoElementException: No element to render on.". Why is that?

**Comment by lindell** [comment]
`NoElementException: No element to render on.` is thrown then the element provided to JsBarcode (the first parameter) does correspond to any page on the webpage.

### This will work
````
JsBarcode("#barcode", "Hi!");
<svg id="barcode></svg>
````

### This will not
````
JsBarcode("#barcode", "Hi!");
<svg id="other-name-barcode></svg>
````

**Comment by pankaja92** [comment]
I tried it. But still, I'm getting the same error. (I'm using svg/img tag inside a 'td' which is generated using Angular ng-repeat

**Comment by lindell** [comment]
Then the tag you want to render on is not loaded when you run JsBarcode. If you want more help you need to provide a running example in some way.

**Comment by pankaja92** [comment]
I send u a mail, sir

**Comment by lindell** [comment]
Changing $scope does not directly change the DOM. You need to run JsBarcode after Angular has updated it.

Here is a blogpost about how to solve it. https://blog.brunoscopelliti.com/run-a-directive-after-the-dom-has-finished-rendering/

So if I read it right this will work.
````
$timeout(function(){
  JsBarcode(...);
}, 0);
````

**Comment by pankaja92** [comment]
'

**Comment by pankaja92** [comment]
Thanks a lot it worked. I'm closing the issue(it wasn't a issue with the library, but with my code)

**Comment by ArmandoAmador** [comment]
@thidasapankaja I know this is an old issue, but how did you figure out how to fix this?

**Comment by kdgyimah** [comment]
> `NoElementException: No element to render on.` is thrown then the element provided to JsBarcode (the first parameter) does correspond to any page on the webpage.
> 
> ### This will work
> ```
> JsBarcode("#barcode", "Hi!");
> <svg id="barcode></svg>
> ```
> 
> ### This will not
> ```
> JsBarcode("#barcode", "Hi!");
> <svg id="other-name-barcode></svg>
> ```

The above worked for me (with React v17.0.1)!
With a slight modification:


 ```
import React, { useEffect } from "react";
import JsBarcode from "jsbarcode";

const App = () => {
  /**
  * effect
  */
  useEffect(() => {
     JsBarcode("#barcode", "Hello");
   }, []);

  return (
    <React.Fragment>
      <svg id="barcode"></svg>
   </React.Fragment>
  )
}
```

**Comment by luananamarques** [comment]
Sei que é antigo, mas se ajudar alguém usei    setTimeout(() => {
        JsBarcode("#barcode", "Hello");
      }, 1000);

que é um tempo até a pagina carregar e dar tempo para renderizar
