### ISSUE TITLE
Canvas installation is a problem.

### ISSUE THREAD

**Issue by rahillakhani** [lindell/JsBarcode#128]
Hello, i am new on Node and trying to build a barcode generator based on data i pass, and i want to write that on pdf.

while I am able to install library for barcode,
unable to install canvas - getting the following error.

 canvas@1.6.3 install /Users/rahil/Documents/projects/tesco/node-pdf-download/node_modules/canvas
> node-gyp rebuild

./util/has_lib.sh: line 31: pkg-config: command not found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/rahil/Documents/projects/tesco/node-pdf-download/node_modules/canvas
gyp ERR! node -v v7.2.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN node-pdf-download@1.0.0 No description
npm WARN node-pdf-download@1.0.0 No repository field.
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "canvas"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.6.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.6.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rahil/Documents/projects/tesco/node-pdf-download/npm-debug.log

Do i really need canvas, or can is there an alternative.
Also, if you could help me to get this in pdf. I am using PDFKIT.

**Comment by lindell** [comment]
The nodejs version is currently requiring node-canvas

Here is how to install it.

https://github.com/Automattic/node-canvas#installation

**Comment by rahillakhani** [comment]
Oh, Let me try
thanks a lot.

**Comment by lindell** [comment]
I don't know what you mean. Install it on the deployed machine as well? And I really think this is a problem concerning node-canvas and not JsBarcode.

**Comment by rahillakhani** [comment]
I'll try to rephrase,

1. do I need "canvas" dependency to get the barcode working on node side?
2. If yes, Can you suggest an alternative? - because I dont really have root access on the machine.

Thanks

**Comment by lindell** [comment]
1. Yes, you need node-canvas.
2. An alternative is https://github.com/metafloor/bwip-js

**Comment by rahillakhani** [comment]
Great, i think bwip would be quiet helpful

thanks a ton for quick reply...

Good day
