### ISSUE TITLE
Printing BARCODE

### ISSUE THREAD

**Issue by abaciocco** [lindell/JsBarcode#129]
Dear lindell:
   Thanks for this great work!
   I'm having problem getting the barcode printed in my Zebra LP 2824 Plus from my HTML, have you some tips to get printed proper?

thank you in advance!

**Comment by lindell** [comment]
What is the problem?

I've seen a lot of people having problem when they are not using SVG as the rendering method (instead using img/canvas).

**Comment by lindell** [comment]
Is the problem solved? If there is no more activity in this issue I will close it.

**Comment by abaciocco** [comment]
Yes! The problem wasnt the api... was windows printer setup.

Thank you so much for your time!!!!

Andrés Baciocco B.
(Enviado desde mi iPhone)

**Comment by ihussain1024** [comment]
@abaciocco 
I'm also having the same problem, not able to print the barcode. Any help please.........
