### ISSUE TITLE
jQuery function is not "chainable"

### ISSUE THREAD

**Issue by Reggino** [lindell/JsBarcode#131]
This is awesome, thanks!

I noticed the `JsBarcode`-jQuery method isn't chainable: it doesn't return the jQuery object, but that is one of the features of jQuery. 

E.g. synchronous barcode-image-source-creation like this: 
 
``` $('<img />').JsBarcode('test').wrap('<div>').parent().html() ```

 would break. Maybe you would consider returning `jQuery(this)` [here](https://github.com/lindell/JsBarcode/blob/master/src/JsBarcode.js#L217)

**Comment by lindell** [comment]
This is actually intended. Since you can chain multiple barcodes like this

````javascript
$('<img />').JsBarcode()
  .options({font: "OCR-B"}) // Will affect all barcodes
  .EAN13("1234567890128", {fontSize: 18, textMargin: 0})
  .blank(20) // Create space between the barcodes
  .EAN5("12345", {height: 85, textPosition: "top", fontSize: 16, marginTop: 15})
  .render();
````

I had to choose between breaking the jQuery standard or remove that functionality all together.

**Comment by Reggino** [comment]
I understand. Thanks for the clarification!
