### ISSUE TITLE
barcode text is not sharp

### ISSUE THREAD

**Issue by javaone199** [lindell/JsBarcode#146]
Hi,

The text below the barcode is not sharp. The demo online with the same options looks fine.
UPC barcode:

```
<canvas id="barcode"><canvas>

JsBarcode("#barcode", "123456789012", {
  format: "UPC",
  width:1,
  height:50,
  fontSize:14
});
```
The text is vague. What is missing?  Does the font of web page affect the font of barcode within the page? 

For code128, the font of text is shown differently from other code such as UPC or EAN13 with the same options, much bigger.

Thanks.
UPC code:
![barcode](https://cloud.githubusercontent.com/assets/10488622/25542037/ec91d046-2c1e-11e7-8e45-454a72aaeead.png)

Code128:
![image](https://cloud.githubusercontent.com/assets/10488622/25542340/1ee0ada0-2c20-11e7-9204-f5bf9b774bbd.png)

**Comment by lindell** [comment]
Test to render on a SVG element instead. Canvas might give problems on for example high DPI screens

**Comment by javaone199** [comment]
Thanks for quick help. SVG works better than canvas. But for the same font size, the font will be bigger if the barcode is flat such as code128, ean8.

**Comment by lindell** [comment]
The font size will be limited on EAN-13 to not clip the barcode lines.

**Comment by javaone199** [comment]
Thanks.
