### ISSUE TITLE
Support for GS1-128

### ISSUE THREAD

**Issue by davidgcalle** [lindell/JsBarcode#148]
Does this library support rendering GS1-128 barcodes? It would be great if it does, cause I not been able to make work other generator's libraries, and really like this one.

**Comment by lindell** [comment]
It seems like GS1-128 is a subset of CODE128 (that JsBarcode supports) but without a start character. This is not supported but could easily be added. Unfortunately I don't have time to add it right now but hopefully some time this week.

**Comment by lindell** [comment]
I'm note sure it I will add GS1-128 as a separate barcode (if you think it is necessary please convince me.)

But you can easily generate these barcodes yourself by manually including the FNC1 character (`\xCF`) in the beginning and any other place if you need.

```
JsBarcode("#barcode", "\xCF12345678", {
  format: "CODE128C"
});
```

**Comment by SanichKotikov** [comment]
Is it the same as Code128(EAN-128)? Then `\xCF12345678` has different looks with `12345678` in Code128(EAN-128).

**Comment by sullivanpt** [comment]
So it turns out EAN128 can contain multiple "application identifiers", where each application identifier is prepended with its own FNC1.  In order to handle more generic EAN128 I've been transforming text to code using:

```
    let text = code // preserve display text
    if (!code.includes('(')) code = FNC1 + code // assume one application ID when no parentheses
    else code = code.replace(/[(]/g, FNC1) // prepend FNC1 to each application ID
    code = code.replace(/[( )]/g, '') // strip spaces and parentheses
    type = 'CODE128C'

    JsBarcode(canvas, code, {
      format: type,
      text
    })
```

See [http://www.makebarcode.com/specs/uccean128.html]

**Comment by SanichKotikov** [comment]
@sullivanpt hi. I have tested a little more and found that bars the same for examples that I found on wiki, gs1 spec and created by 3rd bc generator, and for JsBarcode. No need extra FNC1 in the middle of code. And I found that all my examples completely different with your link. Thoughts?

**Comment by sullivanpt** [comment]
OK, now you have me reading specs. (I was hoping I would not have too, heh).

My understanding now is that when concatenating multiple element strings, the FNC1 is required between some (variable length) element strings, and optional between other (fixed length) element strings. Where element string is an application identifier plus its data.

Given the distribution of "required" and "optional" in the above, I think the code snippet I provided is correct but not optimized for minimum code length.

> Section 7.8.5.1 Predefined length element strings Concatenated element strings constructed from GS1 Application Identifiers with a predefined length SHOULD NOT use a separator character following the element string of predefined length. [...]

> Section 7.8.3 [...] All element strings not included in the predefined table shown in figure 7.8.4-2 MUST be separated by a separator character when followed by another element string in a single barcode. 

Also useful are Section 7.8.5 and Figure 7.8.4-2.

See https://www.gs1.org/sites/default/files/docs/barcodes/GS1_General_Specifications.pdf

**Comment by bugproof** [comment]
I'm new to the library and I see the issue is closed, so what option we need to pass to ensure GS1-128 barcode will be generated?

**Comment by SanichKotikov** [comment]
@bugproof here is an example https://github.com/lindell/JsBarcode/wiki/CODE128#ean128-option-for-code128
