### ISSUE TITLE
Browser support ("".repeat())

### ISSUE THREAD

**Issue by SanichKotikov** [lindell/JsBarcode#155]
Hi,

Looks like I found a small problem:

```js
var zeroes = "0".repeat(size);
```

This code doesn't work if you don't use a polyfill for `repeat` in your code, for example in IE11. I suppose it doesn't make sense to use a polyfill only for one line, and we can replace it by something like this:

```js
const zeroes = new Array(size + 1).join("0");
```

What do you think?

**Comment by lindell** [comment]
It seems like repeat has support down to IE10. But since this library tries to maintain support for IE9 it is true that this should be fixed :)

**Comment by SanichKotikov** [comment]
Unfortunately IE doesn't support this method, even 11 version :(

**Comment by lindell** [comment]
You are correct, looked at the wrong caniuse page :P
