### ISSUE TITLE
to store each barcode values to array 

### ISSUE THREAD

**Issue by kuppas** [lindell/JsBarcode#158]
here i try, to store to array at  each time the method JsBarcode executed through looping but it is not possible please give me any suggestion.  
<script src="JsBarcode.all.min.js"></script>
<p id="Test"></p>
<svg id="barcode"></svg>
<script>
	var a = 1;
	var all = new Array();
	for (i = 01; i <=10; i++) {
		
a=JsBarcode("#barcode", i, {
  format: "CODE39"
});
		
	all[i]=a;
    
	}	
alert(all[1]);
alert(all[2]);
alert(all[3]);
alert(all[4]);
alert(all[5]);
alert(all[6]);
alert(all[7]);
alert(all[8]);
alert(all[9]);
alert(all[10]);
	 document.getElementById("Test").innerHTML = all;
}
	
	</script>

**Comment by lindell** [comment]
I'm not really sure that you want to do. But JsBarcode does not return anything useful but does only manipulate the first parameter which can be an element or an array that will be filled with binary information.

**Comment by lindell** [comment]
I'm closing this issue since I don't get any response.
