### ISSUE TITLE
Interleaved Two of Five

### ISSUE THREAD

**Issue by uebbi** [lindell/JsBarcode#160]
Hi,

I need to generate a bar code in the "Interleaved Two of Five" format but with 44 numbers, how can I do this?

Tks!

**Comment by lindell** [comment]
I would not recommend generating this long of an ITF barcode but I don't see the problem in doing it.

https://codepen.io/lindell/pen/WOQdNL

**Comment by mateusfmello** [comment]
@lindell The Brazilian regulatory body for bank slips defined this standard for the barcode of normal bills.
