### ISSUE TITLE
The input value from getElementById is not working

### ISSUE THREAD

**Issue by kuppas** [lindell/JsBarcode#161]
here i want insert value from input box.in this way i covert server side variable into client  variable by using getElementById method. The converted variable is passed to JsBarcode but JsBarCode shows nothing when i execute in php.
<input type="hidden" name="B1" id="B1" value="<?php echo $x;?>" readonly>		
<script src="JsBarcode.all.min.js"></script>
<p id="Test"></p>
<svg id="barcode"></svg>
<script>
var x=document.getElementById(B1).value;
JsBarcode("#barcode", x);
</script>

**Comment by lindell** [comment]
Works for me.

https://codepen.io/lindell/pen/MoargN

**Comment by kuppas** [comment]
Thank you so much its working!!!!.
If it is possible to print multiple Barcode in a single page with values from 1 to N by using loops.

**Comment by lindell** [comment]
Github issues are not for coding help. Soo please don't use it as it in the future.

But here it is https://codepen.io/lindell/pen/yXYpby
