### ISSUE TITLE
Encode FNC3 startcode

### ISSUE THREAD

**Issue by julienvincent** [lindell/JsBarcode#162]
I'm wondering if there is a way to encode FNC3 for Code128 barcodes using this library?

Specifically I am using [react-native-barcode-builder](https://github.com/wonsikin/react-native-barcode-builder) (which uses this library internally) to generate barcodes on react native.

**Comment by lindell** [comment]
Unfortunatly not right now. But it would be easy to allow for the use of the core CODE128 class which would allow this. I take a look at this.

**Comment by julienvincent** [comment]
If you could take a look that would be very helpful. Thank you very much

**Comment by lindell** [comment]
What is the exact thing you want to encode? Including start character

**Comment by julienvincent** [comment]
Well I'm still a bit hazy on the semantics of this - but I'm wanting to produce a barcode that begins with the FNC3 code, which according to [this table](http://www.adams1.com/128table.html) is the `Ç (ASCII 128)` character. One of the barcodes I want to encode is `{FNC3}91` or `Ç91` which is used by a barcode scanner to change its settings.

**Comment by lindell** [comment]
So the type of CODE128 (A/B/C) does not matter?

**Comment by lindell** [comment]
But it can't be C since FNC3 does not exist in the CODE128C

**Comment by julienvincent** [comment]
I'm not sure. Looking at the table FNC3 is only listed on type A and B

**Comment by lindell** [comment]
Is this what you want to encode?
![image](https://user-images.githubusercontent.com/284868/27002309-0623580e-4ddf-11e7-81c3-81b888f585c4.png)

**Comment by julienvincent** [comment]
Yes that looks correct! Though I can't say for sure as I the barcode scanner I use is at work, but I dropped it into [this decoder](https://online-barcode-reader.inliteresearch.com/) and it produced the same output as my test barcode: `{FNC3}91`

**Comment by lindell** [comment]
I was some time since I created the CODE128 symbology but is seems like I've used this table for reference.
https://en.wikipedia.org/wiki/Code_128#Bar_code_widths

So the FNC characters are supported but not on the characters in the table you've used. 

Here is code to generate what you want to generate 😄 
https://codepen.io/lindell/pen/EXPqzZ

**Comment by julienvincent** [comment]
Ah thats perfect! That is exactly what I need :) Thank you very much for your help! Closing this now
