### ISSUE TITLE
Minification problem?

### ISSUE THREAD

**Issue by markpotts123** [lindell/JsBarcode#163]
I get the following error calling the minified JsBarcode script. It does not occur with the unminified version: 

JsBarcode.all.min.js:2 Uncaught SyntaxError: Invalid regular expression: /^[ -_Ãˆ-Ã]*/: Range out of order in character class

This is under Chrome version 58 (64-bit).

Mark

**Comment by SanichKotikov** [comment]
@markpotts123 try to find which regexp causes this error but can't find it in latest version. Could you provide more information about version and part of code?

**Comment by lindell** [comment]
What I think is happening is that the CODE128 regexpes are minified down to not use hexadecimal syntax but instead is replaced by the actual ASCII characters.

This would not be a problem for most people but my thought is that @markpotts123 is including the script in a way that messes with the encoding since I can include the script without a problem.

**Comment by SanichKotikov** [comment]
Yep, looks like same problem discussed here https://github.com/mishoo/UglifyJS2/issues/54

**Comment by markpotts123** [comment]
I downloaded the latest version. The symptom occurs immediately (in Chrome) with just the example code:

<img id="barcode"/>
JsBarcode("#barcode", "Hi!");

It also occurs with other simple strings so I don't think it relates to the input value. The thread referenced in the previous response contains a detailed discussion of a similar problem.

**Comment by lindell** [comment]
It is indeed not a problem with how you use JsBarcode. The problem as stated before seems to be that you mess something up when including it since it works for with the latest release for other people https://codepen.io/lindell/pen/eRZmeY .

If you think it is something else, please host it somewhere where we can take a look.

**Comment by markpotts123** [comment]
The problem occurs with just a minimal test page:

`<html>
  <script type="text/javascript" src="JsBarcode.all.min.js"></script>
  <body onload="JsBarcode('#barcode', 'Hi!')">
    <img id="barcode"/>
  </body>
</html>`

Under Chrome Version 59.0.3071.86 I get:
Uncaught SyntaxError: Invalid regular expression: /^[ -_Ãˆ-Ã]*/: Range out of order in character class

Under Firefox 53.0.3 I get:
SyntaxError: invalid range in character class

If I switch to the non-minified JsBarcode script it works correctly in both browsers. I am loading the test locally from files on my PC rather than hosting it. I don't know if this could make a difference.

**Comment by markpotts123** [comment]
Sorry about the missing code in the above post. I guess GitHub's 'Insert Code' option doesn't work :-(

**Comment by SanichKotikov** [comment]
@markpotts123 which encoding has your html file?

P.S. one tick can be used only in single line. For multi lines you have to use three ticks ```

**Comment by SanichKotikov** [comment]
@markpotts123 any way, you can build min version of JsBarcode locally with ascii only as described here https://github.com/mishoo/UglifyJS2/issues/54 and share results with us.

**Comment by markpotts123** [comment]
Very interesting! I minified JsBarcode.all.js at https://skalman.github.io/UglifyJS-online/ and the newly minified file worked correctly. I think this must be a character encoding issue of some sort (e.g. ASCII vs UTF-8).

FYI, I obtained the original JsBarcode files by downloading a zip from GitHub and extracting with Windows Explorer. I used Visual Studio to edit my test code as the barcode requirement is part of another project.

Using the re-minified file solves the problem for me, although I am happy to do further tests if it would help fix a more general problem. I have attached the re-minified file that now works for me.
[JsBarCode.min.js.zip](https://github.com/lindell/JsBarcode/files/1066676/JsBarCode.min.js.zip)

**Comment by lindell** [comment]
This is strange. Because if I download the .zip file and edit one of the tests or examples to use the minified version I don't get this problem. What happens if you download the file directly from the repo?

https://raw.githubusercontent.com/lindell/JsBarcode/master/dist/JsBarcode.all.min.js

**Comment by markpotts123** [comment]
I could not include the script directly as both Chrome and Firefox reject it from the repo with an invalid MIME type (text/plain). I tried downloading the file from the repo and including it but still get the original error.

If you are unable to replicate the problem it does look like something associated with my configuration, although I can't think what. These days with layers of opaque OSes, IDEs, frameworks, etc. these sorts of problem seem more frequent ;-). Thanks for all your advice, and for the software which is ideal for my needs.

**Comment by markpotts123** [comment]
I think the problem was that the minified files in the repo are UTF-8 where my HTML did not specify a character encoding and so defaulted to ASCII. When I added `<meta charset="utf-8"/>` to my HTML the downloaded files worked correctly.
