### ISSUE TITLE
How to make EAN-8 Code in Non Flat Format ?

### ISSUE THREAD

**Issue by saaiful** [lindell/JsBarcode#164]
![alt text](https://upload.wikimedia.org/wikipedia/commons/2/26/Barcode_EAN8.svg)

I want EAN-8 In this style, In JsBarcode EAN-13 Comes With This Style.

**Comment by johnwesleysalvador** [comment]
Hi, any updates on this? Our project kind of wants to have this non-flat format for EAN8. It would be really great if this can be implemented :) Thanks!

**Comment by saaiful** [comment]
@johnwesleysalvador use this one https://github.com/saaiful/JsBarcode, it's a fork with flat support.

**Comment by SanichKotikov** [comment]
https://github.com/lindell/JsBarcode/releases/tag/v3.9.0
