### ISSUE TITLE
JsBarcode asynchronously?

### ISSUE THREAD

**Issue by MichelMiola** [lindell/JsBarcode#169]
JsBarcode does the image construction asynchronously? ... because when done in the first made the `ctx.drawImage` of the _CanvasRenderingContext2D_ library the image is not rendered inside, however the second time it is rendered.

version: **3.5.8**

**Comment by lindell** [comment]
It is synchronous. Could you provide a complete example?

What are you trying to accomplish? You want to draw something else above the barcode with `ctx.drawImage` ?

**Comment by MichelMiola** [comment]
First thank you for responding.

I'm doing several a write in the `CanvasRenderingContext2D `plane and I'm assigning the plane to `JsBarcode`.

But I see that at the first moment that creates `JsBarcode `image the same is not shown in the `CanvasRenderingContext2D `plane but in the second moment it is shown. Whenever I change the code (eg _ean13_) it is also not shown in the first one that creates the `JsBarcode `image.

**Comment by lindell** [comment]
This seems strange. Could you please provide example code of this? For example by creating an jsfiddle.

**Comment by MichelMiola** [comment]
Estou achando que o problema é na escrita da imagem em _base64_ no _DOM_ vou realizar um teste. 

Com _onload_ para ver se imagem criou no _DOM_ antes de passar para `ctx.drawImage`

```
var img = new Image();
img.onload = function () {
   alert("image is loaded");
}
img.src = "img.jpg";
```

**Comment by MichelMiola** [comment]
That's right the creation of the base64 in the DOM has a delay until the writing will have to create a promise to write in the base64 DOM.

**Comment by lindell** [comment]
I still don't understand what you think is the issue with the library. If you want me to fix anything I need to be able to reproduce the error.
