### ISSUE TITLE
Responsive SVG

### ISSUE THREAD

**Issue by garygreen** [lindell/JsBarcode#172]
It would be nice if you can specify a width="100%" on the SVG and have it keep it.

At the moment I'm having to do:

```javascript
JsBarcode(".lp-barcode").init();
document.querySelectorAll('.lp-barcode').forEach(function(element) {
    element.setAttribute('width', '100%');
    element.removeAttribute('height');
});
```

**Comment by lindell** [comment]
[You could just do that with CSS](https://codepen.io/lindell/pen/PjavQz). I don't think this qualifies as a big enough use case to be included in the library.

**Comment by lindell** [comment]
Are you still having an issue here or can the issue be closed?

**Comment by matt-oconnell** [comment]
@lindell This CSS approach seems to fail on safari

**Comment by lindell** [comment]
@matt-oconnell This might work instead. https://codepen.io/anon/pen/ayVOwQ

**Comment by matt-oconnell** [comment]
Perfect, thanks!
