### ISSUE TITLE
Barcode quality

### ISSUE THREAD

**Issue by garygreen** [lindell/JsBarcode#174]
I'm currently generating a UPC barcodes in SVG (to be printed at an exact size in mm)
However when using a barcode verifier/quality scanner the barcodes always come out as a fail - the scanner grades the barcode quality by B to F grade.

![image006](https://user-images.githubusercontent.com/1702638/28128793-e2403a2a-6728-11e7-83f9-420d8c385979.jpg)

Any idea why this could be? The library seems to gear towards outputting the barcode on screen by defining the barcode widths in pixels - maybe this is a problem when you are outputting small barcodes or outputting to a specific size in mm because it's not precise enough?

Checking another tool https://www.jacoballred.com/barcode/index.php?code=021200300608&encoding=UPC-A&fg=%23000000&bg=%23FFFFFF&multiplier=0.5
This is defining the widths as inches and seems to be using a much finer decimal place.

**Comment by lindell** [comment]
So you are using JsBarcode and printing the barcodes on a paper and then using that tool to verify? That should not be a problem.

What could (and will almost be guaranteed to) be a problem is if you try to specify a width on the entire barcode if the barcode is not very big since the one barcode line will be fractions of pixels.

**Comment by garygreen** [comment]
Basically the below is what we're trying to achieve... we print out a load of barcodes onto an A4 page that must be a fixed width / height as it's going to be cut up and printed on different tickets.

I suspect it is down to the height/width definitions conflicting with the `height` and `width` options that you supply to JsBarcode... I've played around with the `preserveAspectRatio` svg option but not had much luck with that, or the `shape-rendering` option.

https://jsfiddle.net/x6pq3a3w/1/

**Comment by garygreen** [comment]
PS - At the moment we use a PHP library for generating the barcodes in PNG format with 4 times the resolution and scale it down, this gives us a good quality barcode under the same width / height as on that js fiddle example. However, as we put hundreds of barcodes on a printout it generates a huge filesize 300+ Meg, we generate thousands of the files so obviously need a way to generate a barcode in SVG / vector format that scales well and gives just as good quality.

**Comment by lindell** [comment]
Firstly, I can say with confidence that the width/height aspect has nothing to do with it. 

Second, I did not get an answer on the question.
> So you are using JsBarcode and printing the barcodes on a paper and then using that tool to verify? 
And additionally, are you printing the PNG barcodes with the same size as the ones you generate by JsBarcode?

**Comment by garygreen** [comment]
> we print out a load of barcodes onto an A4 page

Yes we are then using a tool to verify the barcode quality.

**Comment by lindell** [comment]
I'm sorry, I thought that was a description of what you was try to archive not the verification process.

In that case. Could you please take a picture of the both barcodes (the PHP one and the JsBarcode one) side by side so I can see how the barcode is getting warped?

Also, what is the tool you are using? 🙂

**Comment by lindell** [comment]
Is there any update on this issue?

**Comment by garygreen** [comment]
I'm not much can be done here because the barcodes that are rendered are technically the same, have same widths etc I think it's just the nature of SVG rendering. Bit lost what to do tbh will probably just have to stick to rendering in PHP with PNG barcodes.
