### ISSUE TITLE
Email rendering

### ISSUE THREAD

**Issue by francoom** [lindell/JsBarcode#176]
Hello. I am trying to embed the bar code on a text/html type of email. I was able to render it on the html site, and I would also like to put the bar code on an html type email. I tried using the same script as on the html site, but won't show on the email.

Code used on HTML Site and Email:
```
<svg class="barcode"
jsbarcode-format="auto"
jsbarcode-value="12345"
jsbarcode-width="1"
jsbarcode-margin="0"
jsbarcode-textmargin="0"
jsbarcode-fontoptions="bold"
jsbarcode-fontsize="15">
</svg>
```

**Comment by lindell** [comment]
You can't run javascript in emails. Simple as that. Closing the issue directly. If you have more questions, please ask.

**Comment by lindell** [comment]
[This shows you how to use JsBarcode to generate an canvas](https://github.com/lindell/JsBarcode#nodejs) that then can be saved to an png.
