### ISSUE TITLE
Create barcode on dynamic element

### ISSUE THREAD

**Issue by PomegranateApps** [lindell/JsBarcode#177]
Is it possible to create a barcode on a dynamic element? The documentation only shows how to create barcodes on elements that are already in the DOM.

```
// How do I create a barcode on this element?
var element = document.createElement("svg");
```

**Comment by lindell** [comment]
Hello. This should absolutely be added to the wiki documentation.

But it is possible, just pass the element in the first parameter. One tricky thing thou, [creating svg elements is a bit different from other elements](https://stackoverflow.com/a/8215105/838789)
````javascript
var barcode = document.createElementNS("http://www.w3.org/2000/svg", "svg");
JsBarcode(barcode, "hello");
````

**Comment by PomegranateApps** [comment]
Thanks! That worked great.
