### ISSUE TITLE
can not render the barcode at a specific location!

### ISSUE THREAD

**Issue by kavinwang** [lindell/JsBarcode#178]
I hava a canvas which will be rendered with a title, some descriptions and a barcode, I can render the title and the descptions.  but when I render the barcode , erverything is gone but the barcode left ! That is not what I wanted !

Is it any way I can do my job?
Is this a bug or new requirement ?

thanks!

**Comment by lindell** [comment]
This is intentional. If you want to draw the barcode on another canvas just copy the barcode to that context.

```
var ctx = youCanvas.getContext('2d');

var barcodeCanvas = document.createElement('canvas');
JsBarcode(barcodeCanvas, "test");

ctx.drawImage(barcodeCanvas, 25, 50);
````

Where 25 and 50 is the x and y coordinates.

**Comment by lindell** [comment]
Is this solution working for you? Can I close the issue?
