### ISSUE TITLE
text options removing the space and * from the string that I am appending.

### ISSUE THREAD

**Issue by ravikant31** [lindell/JsBarcode#179]

**Comment by lindell** [comment]
Please provide an example.

**Comment by ravikant31** [comment]
function (barcodeString) {
    var text = tranc.split('').join('  ');
    $scope.JsBarcode = new JsBarcode("#barcode", barcodeString, {
            format: "CODE39",
            displayValue: true,
             text: " * " + text + " * "
      });
 };

So I am adding space and * but when the final barcode is generated I don't get the space and *.
This was working fine in <canvas> but the issue started only after i changed it to <svg> for clarity.

![svg](https://user-images.githubusercontent.com/11021706/28470057-14263c86-6e56-11e7-8993-0a054958afbf.PNG)  The svg image
![canvas](https://user-images.githubusercontent.com/11021706/28470063-1a407a1e-6e56-11e7-8f7e-aa192a43c66d.PNG) The canvas image

**Comment by lindell** [comment]
First why are you calling **new** JsBarcode() and then saving in to an Angular scope variable? 

Second, I have no problem with this.

https://codepen.io/lindell/pen/WEewLx

**Comment by ravikant31** [comment]
Thanks for quick response !
We are calling **new** JsBarcode() because we get build error saying **missing new**.
I saw it works here in the codepen but somehow it removes the * in my application. Will revert back to you.

**Comment by ravikant31** [comment]
Seems its a lint error because of the capitalized J in JsBarcode().

**Comment by ravikant31** [comment]
The * truncating is fixed. I was using an older version of library. It works fine now. But it still removes the space that we add in string tried with your codepen as well. The space is truncated in case of svg only. 

And we have to use new if we are using JSLint. Thanks for support

**Comment by lindell** [comment]
How the spaces are rendered is due to how SVG (and HTML) handles multiple spaces. I'm not sure it's a good idea to for example replace the spaces with some other space character to avoid this in the library, it could cause problems for other people. But if you want to do it yourself you can just replace the spaces with the `\u00A0` character like this https://codepen.io/lindell/pen/PKYMeR
