### ISSUE TITLE
Transparant Barcode

### ISSUE THREAD

**Issue by fridzema** [lindell/JsBarcode#180]
Hello, 

Is there any option/method how i can generate transparant barcodes, cant find a thing in the documentation or wiki?
I have tried setting the background option to 'transparant', but unfortunately it creates a black background.

**Comment by SanichKotikov** [comment]
Hi. Should works for svg/canvas

```js
JsBarcode("#code128", "Hi!", { background: 'rgba(0,0,0,0)' });

// Also works for me
// JsBarcode("#code128", "Hi!", { background: 'transparent' });
```

**Comment by lindell** [comment]
As @SanichKotikov said. This should work.

https://codepen.io/lindell/pen/xLGxQJ

**Comment by fridzema** [comment]
Hmmm i guess i did something else wrong:(

Thanks for your help guys, i appreciate it!
