### ISSUE TITLE
request: make it available in maven repository

### ISSUE THREAD

**Issue by javaone199** [lindell/JsBarcode#182]
It would be great if it is available in maven repository so that it can be managed by Gradle build.

**Comment by javaone199** [comment]
// https://mvnrepository.com/artifact/org.webjars.bower/JsBarcode
compile group: 'org.webjars.bower', name: 'JsBarcode', version: '3.3.16'

It is too old.

**Comment by lindell** [comment]
Sorry for the long response, been disconnecting from github during the vaccation. 

I have no idea what maven repository is so the upload is made by someone else.
