### ISSUE TITLE
How to set total width instead of bar's width ?

### ISSUE THREAD

**Issue by MonkeyDoll** [lindell/JsBarcode#189]
Hello,
I am doing a page to print batch of barcodes and each one will be same size but different text and length of text. anyway to do this ?

**Comment by lindell** [comment]
There is no way to do this currently. For print it could be useful but I'm afraid people will missuse it on screens and then complain that the library isn't working. Either way I have no plans to implement it right now but could be open to a PR

**Comment by cguldner** [comment]
This seems like an essential feature, please consider adding this. Or at least a way to have the library let the width and height properties be defined by the `svg` element directly. I am unable to use this library without this feature

**Comment by jjacobson** [comment]
Agreed, this is much needed.

**Comment by ziaulrehman40** [comment]
Need for printing, leabels are mostly used for printing so this is essential

**Comment by mglidden** [comment]
I wrote a wrapper (using ReactBarcode) to get the rendered width and then adjust the bar width to scale correctly. Note that this will add a second render.
```
import React, { useState, useRef, useEffect } from 'react';
// @ts-expect-error
import ReactBarcode from 'react-barcode';

export type Props = {
  height: number;
  width: number;
  value: string;
};

function numberOfBars(value: string): number {
  // from https://www.adams1.com/128code.html
  // this is correct as long as there aren't consecutive numbers.
  return 11 * value.length + 35;
}

export default function BarcodeWidget(props: Props) {
  // The ReactBarcode API only takes bar width as a param, but we want to scale to the width argument
  // We'll start with an estimate for the width, based on code128.
  const [barWidth, setBarWidth] = useState(props.width / numberOfBars(props.value));
  const barcodeEl = useRef(null);

  // Once we've rendered, use the actual width to figure out what the barWidth should have been.
  useEffect(() => {
    if (!barcodeEl || !barcodeEl.current || props.width == null || props.height == null) {
      return;
    }
    const widthString = barcodeEl.current.refs.renderElement.getAttribute('width');
    const trueWidth = parseInt(widthString.split('px')[0], 10);
    const scale = props.width / trueWidth;
    setBarWidth(barWidth * scale);
  }, [props.width, props.height, barcodeEl?.current]);

  return (
    <ReactBarcode
      ref={barcodeEl}
      value={props.value}
      width={barWidth}
      height={props.height}
      margin={0}
      displayValue={false}
    />
  );
}
```

**Comment by ChrisTregaskis** [comment]
I came across the same issue. Applying `maxWidth` inline solved it for me. In my instance, I wanted it to fit a width set by the parent.

```
  useEffect(() => {
    if (value) {
      try {
        JsBarcode(renderElement.current, value, {
          format,
          width,
          height
        });
      } catch (error) {
        console.error(error);
      }
    }
  }, [ value ]);

  return (
    <img style={{ maxWidth: "100%" }} ref={renderElement} alt={`barcode: ${value}`} />
  );
```

**Comment by C17AN** [comment]
> I came across the same issue. Applying maxWidth inline solved it for me. In my instance, I wanted it to fit a width set by the parent.

This code works, thanks a lot! 😄
