### ISSUE TITLE
Range out of Order

### ISSUE THREAD

**Issue by yashgarg1232** [lindell/JsBarcode#190]
Hello,

While using the v3.8 release, I am getting the following error: `Invalid Regular Expression`, however, the library works like a charm when using v3.6

![capture](https://user-images.githubusercontent.com/6193780/30573872-2328034e-9cab-11e7-9553-d0e9d41704eb.PNG)

The sample is the wiki guideline for browser setup.
Thanks.

**Comment by lindell** [comment]
This is because of wrongly downloaded or included code. I have been thinking about compiling the code in another way to avoid this issue. I would increase the size with a few bytes but it would be a small price

**Comment by yashgarg1232** [comment]
I have been wondering about _wrongly downloaded or included code_ in the comments. I think, I just renamed the file, to have all lowercase alphanumeric characters rather than J and B being uppercase. I think you are right, maybe increase in size by few bytes is a better price to pay rather than risking the proper functionality of the library.

**Comment by lindell** [comment]
The name of the file has nothing to do with this. It's rather the charset of the file you include the file from/the library itself. Do you use UTF-8 on both?

**Comment by SanichKotikov** [comment]
`<meta charset="UTF-8">` should solve the issue
