### ISSUE TITLE
Feature request: what about QRCode

### ISSUE THREAD

**Issue by ayyash** [lindell/JsBarcode#193]
Any plans to include qrcode generation as well?

**Comment by lindell** [comment]
This library is focused on 1D barcodes. There are many libraries that focuses on soely QR-codes

**Comment by beylkhanovdamir** [comment]
@lindell hummm, sounds interesting, I need to get the another one plugin for qr codes and I should keep your one for 1D barcodes only, great thoughts...

**Comment by bitsnaps** [comment]
This seems to be a good fit for QrCode (aka. datamatrix)
https://github.com/davidshimjs/qrcodejs
