### ISSUE TITLE
Question: how to import a single sub library in NodeJs

### ISSUE THREAD

**Issue by ayyash** [lindell/JsBarcode#194]
in NodeJs you would, to get the full library
`var code = require('jsbarcode');`

What is the way to import only one sub library? Code128 only for example

**Comment by lindell** [comment]
You can't. But what is the reason for it? Do you want to minimize the size? Then use some sort of tree shaking like webpack + minification like uglify.

**Comment by ayyash** [comment]
During development I thought I could reduce the amount of code imported but it turned out the difference in size isn't huge anyway
