### ISSUE TITLE
Barcode Not Scanning 

### ISSUE THREAD

**Issue by nugwuegbu** [lindell/JsBarcode#199]
Hi lindell, I used JsBarcode in my application to enable me print barcodes from browser and scan the items using a Barcode scanner but after printing, i discovered that the scanner is unable to read the barcode, below is my code please i don't know what i am doing wrong, in addition, how can i make this to be printable from a browser to a barcode printer such that each barcode is printed as a label?

<script type="application/javascript" src="jquery-3.2.1.min.js"></script>
<script type="application/javascript">
    var s_numbers = window.localStorage.getItem('snumbers');
     var vals = s_numbers.split(",");
    var i;

    for (i =0; i<vals.length; i++){
        console.log(vals[i]);
        $("#pr").prepend('<canvas class="BarcodeLabel"  id="'+vals[i]+'"></canvas><div class="page-break"></div>');
        var cvs = document.getElementById(vals[i]);
        JsBarcode(cvs,vals[i],{width:1,height:80,margin:10,format:"CODE128",font:"monospace",background:"#ffffff",lineColor:"#000000"});
    }
</script>

**Comment by lindell** [comment]
1. Does it work to scan from the website?
2. Do you use svg or canvas to print on?

**Comment by nugwuegbu** [comment]
lindell , Thanks for the response, it wasn't working to scan from the website, actually i was using canvas but i have changed it to svg and it works, but one more question please which browser is best for printing the barcodes? i used chrome but it can only print one at a time but i need to print in serial. thanks

**Comment by ramanbalaji** [comment]
Hi Lindell, Do you have plans to make the JsBarcode scan barcodes?  I'm looking for an ionic angular js barcode scanner (for Android devices) that scans MSI barcodes.  The ionic native barcode plugin does not work in Android devices.  Any help is greatly appreciated.

**Comment by Sanjay7035** [comment]
I am facing same issue with JsBarcode (CODE128). I am using svg but it's not getting scanned by barcode scanner. I am able to scan other barcodes which are available on google. Please find my generated barcode below.

![image](https://user-images.githubusercontent.com/29940974/36970598-2165c970-208f-11e8-9106-76d38a3a0d8f.png)

**Comment by lindell** [comment]
@Sanjay7035 The barcode is scanning just fine. Your scanner does probably not support CODE128.

https://i.imgur.com/5p7Ic6Y.jpg

**Comment by Sanjay7035** [comment]
Thanks for the prompt response. I will check with another scanner.
