### ISSUE TITLE
Complete validate function and auto detectand prevent error

### ISSUE THREAD

**Issue by JohnAdib** [lindell/JsBarcode#203]
Hi and thanks for lib;)
Some tips to improve

- it's better to automatically detect format of barcode
- complete validate function to return format
- prevent error in code if string of code is not valid on selected format

**Comment by SanichKotikov** [comment]
Hi,

> it's better to automatically detect format of barcode
> complete validate function to return format

https://github.com/lindell/JsBarcode/issues/186#issuecomment-325422746

> prevent error in code if string of code is not valid on selected format

You can use `valid` option or `try/catch` to avoid it.
