### ISSUE TITLE
GTIN-14

### ISSUE THREAD

**Issue by shayneslitehouseinc** [lindell/JsBarcode#207]
Is there an option to have the spaces added in the human-readable numbers below the barcode for a GTIN-14?

https://www.gtin.info/

Format ITF14 isn't adding those spaces. 

This number: 20017661004122 should read 2 0017661 0041 22.

Thanks!

**Comment by lindell** [comment]
Hi

You can easily format the text however you want with the text option.

https://codepen.io/lindell/pen/KyjKKr

**Comment by shayneslitehouseinc** [comment]
Thanks Johan,

I should have kept looking before I sent you an email ;)

Have a good one!
