### ISSUE TITLE
Update README to recommend canvas-prebuilt

### ISSUE THREAD

**Issue by sullivanpt** [lindell/JsBarcode#213]
I'm just getting started with this awesome library, so take my suggestion with a huge grain of salt.

I'm using this for SSR and I wasted a lot of time trying to get canvas installed on my Windows 10 box.  Then I discovered [canvas-prebuilt](https://www.npmjs.com/package/canvas-prebuilt) and my problems magically went away.   It might be a good idea to recommend canvas-prebuilt as the easiest way to get started using jsbarcode on nodejs.

**Comment by sullivanpt** [comment]
Following up, my use case includes CentOS 6 which it turns out is not supported by canvas-prebuilt.  I ended up jettisoning the entire canvas/cairo dependency and slapping together a "junk yard" canvas 2d implementation built on Jimp.

For anybody with similar constraints the jimp based solution is here; I'd love some help cleaning it up. [jimp-canvas](https://www.npmjs.com/package/jimp-canvas)

**Comment by lindell** [comment]
Hello @sullivanpt.

Sorry for the late response. It would be great to not have the compile requirement as you mention. But it would also need to be able to do it for most popular platforms, so jimp does indeed seem like a good solution if you could get it to work well. Right now, with node-canvas, the barcodes are rendered pixel perfect compared to browsers which a replacement (almost) has to fulfill. 

I would really appreciate if you manage to do that and would gladly change the recommended library in that case :)

**Comment by SanichKotikov** [comment]
There is another way to solve canvas issue > using Docker.
Create 3 files in project folder (for example):

`.dockerignore`:
```
**/node_modules
```

`Dockerfile`:
```
FROM node:8

RUN apt-get update && apt-get install -qq libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++

RUN mkdir -p /frontend
WORKDIR /frontend
COPY ./ ./

RUN npm install

CMD npm test

EXPOSE 3000
```

`docker-compose.yml`
```
version: '2'
services:
  jsbarcode:
    build:
      context: ./
    volumes:
      - ./src:/frontend/src
    ports:
      - 3000:3000
```

Then run:

`npm install --ignore-scripts`
`docker-compose up`

**Comment by sullivanpt** [comment]
@SanichKotikov just to be clear, you are using Docker to spin up a newer version of the OS (e.g. CentOS 7) hosted on an older OS; and then running your entire node server stack inside that VM, yes?  That's pretty clever.   You could use canvas-prebuilt with this idea and save some additional headache.  On the other hand, it appears even Docker itself doesn't support a CentOS 6 box as host https://success.docker.com/article/Compatibility_Matrix, so I think it doesn't help my use case.  It should work well for Win10 though, thank you.

I am still using the jimp-canvas solution for my CODE128 renders, but as Lindell points out it's not flexible, nor pixel perfect.
