### ISSUE TITLE
Print barcode label

### ISSUE THREAD

**Issue by ihussain1024** [lindell/JsBarcode#214]
Hello @lindell 
I have been working on a project that prints barcode for each user. I have tried different barcode library, but not succeeded. How can I print barcode label by using your library, can you help me ?
Any help will be appreciated..

**Comment by SanichKotikov** [comment]
Hi. Could you explain what do you mean by
> print barcode label

?

**Comment by ihussain1024** [comment]
@SanichKotikov 
I mean barcode sticker.

**Comment by AmrGamalAoiis** [comment]
did you solve this problem?
i need to solve it but i can't , i have a problem in size

**Comment by ziaulrehman40** [comment]
Size issues here as well....
