### ISSUE TITLE
JsBarcode node.js canvas 

### ISSUE THREAD

**Issue by jam29** [lindell/JsBarcode#217]
Hi,
I am using your node module in order to create a pdf file with many labels. The problem is that barcode created is fuzzy. You can see pdf and node.js code here:
[https://openlab.ghost.io/node-js-barcode/](https://openlab.ghost.io/node-js-barcode/)
 Do i miss options  ? Thank you for your help please if possible.

**Comment by lindell** [comment]
You are using a width that is not an integer, `0.8`. Change this to `1` or `2` should solve the problem.

**Comment by jam29** [comment]
Thank You lindell ,
barcode is better , you can see result at bottom here : https://openlab.ghost.io/node-js-barcode/  . Is it possible to create better font ? Thanks
