### ISSUE TITLE
Being able to pass a function as the text option

### ISSUE THREAD

**Issue by coolreader18** [lindell/JsBarcode#220]
Basically:
```javascript
JsBarcode("#barcode", "Input Text", {
  text: function(inputText) {
    return "* " + inputText + " *" // if I wanted to make it fancy-looking or something like that
  }
})
```
If I were to submit a PR for this, where should that go? I thought maybe [Barcode.js](/lindell/JsBarcode/blob/master/src/barcodes/Barcode.js), but I'm not completely sure.

(Also, feedback welcome)

**Comment by SanichKotikov** [comment]
Hi,

I'm not sure what for you need this, and why you just don't do it like this:
```
function(inputText) {
  // if I wanted to make it fancy-looking or something like that
  const text = "* " + inputText + " *";
  JsBarcode("#barcode", "Input Text", { text });
}
```

Maybe I missed something?
