### ISSUE TITLE
Error: Not supported type to render on

### ISSUE THREAD

**Issue by pureexe** [lindell/JsBarcode#221]
Uncaught Error: Not supported type to render on

I need to create dynamic barcode to <div id="info"> but it error

to reproduce bug.
https://jsfiddle.net/hb9nr62q/

- best regards

**Comment by lindell** [comment]
SVG elements [are a bit special](https://stackoverflow.com/questions/8215021/create-svg-tag-with-javascript) and can therefore not be created with `document.createElement`.

This works fine.
https://jsfiddle.net/hb9nr62q/1/

**Comment by pureexe** [comment]
@lindell Thank you, now it work. close issue.

**Comment by patill** [comment]
Wow, thank you for that solution! I worked on this for three days!
You might add this to a FAQ or something?
