### ISSUE TITLE
Not working in IE. Works great in Chrome!

### ISSUE THREAD

**Issue by ghost** [lindell/JsBarcode#224]
Code works great in Chrome, no luck in IE.

**Comment by SanichKotikov** [comment]
Works fine in IE

**Comment by DanceKiddle** [comment]
Not work in IE8 and lower version , it cause **Error:Identifier expected**.
I use `JsBarcode.all.min.js` script.

**Comment by SanichKotikov** [comment]
@DanceKiddle hi! I suppose this lib is designed for IE9+ (or maybe IE10+).
