### ISSUE TITLE
Text and value

### ISSUE THREAD

**Issue by nomercy89** [lindell/JsBarcode#225]
Is there a way to set a text for example to the top of barcode and the value to the bottom? 
For example: i want set the value of barcode to 12345 and add the name of product to the top of barcode.

**Comment by zurez** [comment]
Same issue here.

**Comment by SanichKotikov** [comment]
@nomercy89 @zurez I believe it doesn't look like a part of standards, but you can do it by `html+css` or `Canvas API`.

**Comment by justinribeiro** [comment]
If you're using canvas output, you can draw on the resulting canvas output since JsBarcode is synchronous. Example:

```
const canvas = document.querySelector('#barcode');
const ctx = canvas.getContext('2d');
const barcodeMargin = 35;

JsBarcode(canvas, '000001', {
  format: 'CODE128',
  ean128: false,
  height: 150,
  width: 2,
  fontSize: 20,
  margin: barcodeMargin,
});

const x = (-canvas.width / 2) + barcodeMargin;
const y = barcodeMargin - (barcodeMargin / 2);

ctx.font = 'bold 20px Monospace';
ctx.textAlign = 'center';
ctx.fillStyle = 'black';

ctx.fillText("Justin Says Hello".toUpperCase(), x, y, canvas.width);
```

Which would result in:

![image](https://user-images.githubusercontent.com/643503/37248595-2517fcd2-248b-11e8-88fd-f794eeb449d9.png)

**Comment by sanjeevuideveloper** [comment]
above code is not working as intended to, please help me

**Comment by sanjeevuideveloper** [comment]
var JsBarcode = require('jsbarcode');
const { Canvas } = require("canvas");
 var canvas = new Canvas();

  
JsBarcode(canvas,  text,
  {
    format:"CODE128",
    ean128: false,
    height: 50,
    width: 2,
    fontOptions:"bold",
    fontSize:15,
    marginTop:0,
    paddingTop:0
   }
  );
var png = canvas.toDataURL('image/png',1);
