### ISSUE TITLE
EAN autodetection bug

### ISSUE THREAD

**Issue by alpha-and-omega** [lindell/JsBarcode#229]
EAN autodetection fails with javascript error:
From example at https://github.com/lindell/JsBarcode/wiki/EAN:
`JsBarcode("#barcode", "5901234123457", {format: "EAN"});`
TypeError: api.options(...)[options.format] is not a function

**Comment by SanichKotikov** [comment]
@alpha-and-omega hi. Thanks. Looks like the wiki page is a little outdated, cuz there is no EAN format in the code base.

**Comment by alpha-and-omega** [comment]
Is it possible to implement this feature ?

**Comment by alpha-and-omega** [comment]
Thanks!

**Comment by orcunozbay** [comment]
will you fix it ? are you have a plan ?
