### ISSUE TITLE
Encode special ASCII  ( \r, tab etc) 

### ISSUE THREAD

**Issue by devreq** [lindell/JsBarcode#23]
Hi, recognizes  the lib special ASCII characters like \r , TAB and etc ?

**Comment by lindell** [comment]
It should in the barcodes that support it, the only one that do it is CODE128 (the default). But just saw that it does not validate those characters as valid. I fix this soon.

**Comment by lindell** [comment]
I'm sorry, what I just said was wrong. Even CODE128 does not support \r or TAB. If you have a barcode that does support it I might implement it in the future.

http://sv.wikipedia.org/wiki/Code_128
