### ISSUE TITLE
Supporting multiple codebars throught new window

### ISSUE THREAD

**Issue by kalihos** [lindell/JsBarcode#231]
Hi.

I'm using this powerful component into a cloud application. While it works fine when I try to send that "bar-image" throught a new window, I'm not able to get it working with dynamically generated code. I say: I define date into my controller such as:
printData +=  '<script>JsBarcode("#barcodeReceta", "' + objPres[i].numrecetacodif + '", { format:"CODE128", height:74});</script>'; 
And later I define, also into my controller:
printData += '<div><label class="d28" rel="nofollow"><img class="barcode" id="barcodeReceta" /></label></div>';

This works well when doing:
var newwin = window.open('', '_blank', 'width=925,height=620');
newwin.document.open();
newwin.document.write(HtmlCab + recetatext + HtmlFoot);
newwin.setTimeout("window.print()", 3000);

However, if I try to draw N barcodes in the same page, I modify the code to get:
printData +=  '<script>JsBarcode("#barcodeReceta' + i + '", "' + objPres[i].numrecetacodif + '", { format:"CODE128", height:74});</script>'; 
And later I define, also into my controller:
printData += '<div><label class="d28" rel="nofollow"><img class="barcode" id="barcodeReceta' + i + '" /></label></div>';

But, when launching, I can't get any barcode drawn into my page. Only if I replace the dynamically written value 'i' with its real value, in a static way, I get the barcode (and it's always the last of the list).

Can you please help me?

Thanks in advance.

**Comment by lindell** [comment]
This does not seem to be any issue with JsBarcode, therefore I'm closing this issue.
