### ISSUE TITLE
Can we remove the tab or enter at the end of the barcode?

### ISSUE THREAD

**Issue by neverender24** [lindell/JsBarcode#241]
When I generate I think it auto add enter/tab, can we get rid of that also?

**Comment by lindell** [comment]
Please provide an viewable example with the code that produces this

**Comment by neverender24** [comment]
actually I got it right...with all the example given. But I noticed when scanning it jumps to another input after the scan. I think the last 3 bars generated is a Tab/Enter special characters (not sure). I just want to know if possible when I scan, it won't go to another input box.

**Comment by lindell** [comment]
I'm sorry but I have no idea what your problem is. If you think there is a problem with JsBarcode. Please provide an viewable example
