### ISSUE TITLE
How do I create barcode image file by node?

### ISSUE THREAD

**Issue by scorpioRED** [lindell/JsBarcode#242]
Hi !
I have try code from example

```
var JsBarcode = require('jsbarcode');
var Canvas = require("canvas");

var canvas = new Canvas();
JsBarcode(canvas, "Hello");
```

So where I can find result ?

**Comment by ItsTarik** [comment]
You should get the base64 data from the Canvas instance according to the [docs](https://github.com/Automattic/node-canvas#canvastodataurl-sync-and-async). by:

`const dataUrl = canvas.toDataURL();` then you could preview it using img like so:
``<img src='${dataUrl}' />`` .
