### ISSUE TITLE
How do i get the raw SVG (as a string)?

### ISSUE THREAD

**Issue by FlandersBurger** [lindell/JsBarcode#245]
I'd like to use the SVG output and embed it into another SVG file (so I can make labels with barcodes). 
How can I have the SVG returned as a string instead of having it render a canvas?

**Comment by marcusy3k** [comment]
Yes, I want this too, how to get the SVG Path String of the barcode?  e.g. 'M 10 10 l 100 0 l 0 100 l -100 0 Z'

**Comment by SanichKotikov** [comment]
You can do anything with SVG after JsBarcode, for example you can read `innerHtml` or something other.

**Comment by jonian** [comment]
@SanichKotikov that is not a proper solution. @marcusy3k if you want to get an svg path you can use the code below:

```js
import { CODE128 } from 'jsbarcode/src/barcodes/CODE128'

const barcodeToSVG = (text, options = {}) => {
  const pixelSize = 0.3
  const rowSize = 30

  const offsetX = 2
  const offsetY = 18

  const object = new CODE128(text, options)
  const result = object.encode()

  const binary = result.data
  const pathes = []

  for (let col = 0; col < binary.length; col++) {
    if (binary[col] == 1) {
      const x = (parseInt(col) * pixelSize) + offsetX
      const v = rowSize * pixelSize

      pathes.push(`M${x},${offsetY}h${pixelSize}v${v}h-${pixelSize}z`)
    }
  }

  return pathes.join('')
}
```

You can adjust `pixelSize`, `rowSize` and `offsetX/Y` to place the barcode in the desired position and size. 
This can become more generic and support width/height and other options if it is integrated in this library.
