### ISSUE TITLE
How to add text in top and bottom of barcode like alternative text ?

### ISSUE THREAD

**Issue by ShyamalKapatel** [lindell/JsBarcode#246]
I want to add text in top and bottom of the barcode that just alternative text, not barcode value. I know we can add alternative text either top or bottom but I want to add it in both places.
I am using angular-barcode which uses this library

**Comment by reda134** [comment]
i want also to add 2 texts at the top and 2 text at the bottom.
Any idea how to do that ?

**Comment by SanichKotikov** [comment]
@ShyamalKapatel @reda134 you can do anything with canvas or svg after you got it from the library.
