### ISSUE TITLE
Asterisk prevents barcode from rendering? 

### ISSUE THREAD

**Issue by BennetLeff** [lindell/JsBarcode#252]
According to wikipedia, an asterisk is supported by barcode 39. However, when I try to put asterisks on either side of a string to print as a bar code, the code no longer renders. My html follows:

```php
<svg id='code39'></svg>
<script type='text/javascript'>
$(document).ready(function() {
	JsBarcode('#code39', '* barcode-text *', {format: 'code39'});
});
</script>
```

Without the asterisks, the code runs fine. This html is actually embedded in PHP but I tried using asterisks in the codepen examples and it still does not work.

**Comment by thisisagithubaccounta** [comment]
Asterisks in code39 are the start and stop characters, meaning that although technically you can encode the character it would not work as expected. It looks like your trying to add the start and stop character above, but the library handles this for you.
