### ISSUE TITLE
Ionic: convert barcode to image

### ISSUE THREAD

**Issue by fahmisaad** [lindell/JsBarcode#254]
Hi, i successfully create barcode using this library, but i try to convert it to image. Can someone guide me on how to do it? 

i tried this but i don't know what to do after that?
    var canvas = document.createElement("canvas");
    JsBarcode(canvas, "Hello");
    const dataUrl = canvas.toDataURL();

**Comment by SanichKotikov** [comment]
Sorry, but the issue doesn't related to the library.
