### ISSUE TITLE
Browser cannot render a Barcode

### ISSUE THREAD

**Issue by wilton323** [lindell/JsBarcode#258]
My goal is to render a code128 barcode in a simple webpage (not NodeJS), but the barcode could not be rendered in my the webpage.

Here is the html source code:

`<html>`
`	<head>`
`		<script src="JsBarcode.code128.min.js"></script>`
`		<script>`
`			var element = document.getElementById("barcode");`
`			JsBarcode(element, "Hi!");`
`		</script>`
`	</head>`
`	<body>`
`		<p>Hi, this is normal text, below is barcode.</p>`
`		<!--<canvas id="canvas"></canvas>-->`
`		<!-- or -->`
`		<img id="barcode"/>`
`		<!-- or -->`
`		<!--<svg id="barcode"></svg>-->`
`	</body>`
`</html>`

Error seen by Chrome:

Uncaught Error: Not supported type to render on
    at new e (JsBarcode.code128.min.js:2)
    at o (JsBarcode.code128.min.js:2)
    at A (JsBarcode.code128.min.js:2)
    at test.html:6

Result:

![image](https://user-images.githubusercontent.com/42230429/43881244-28a299e6-9bde-11e8-9761-9f0356d5d0bf.png)

I have tried svg, img and canvas tag, but all of them doesn't work. Can anyone provide any assistance?

**Comment by SanichKotikov** [comment]
@wilton323 two mistakes:
- forgot `<meta charset="UTF-8">`
- your code runs scripts before any tags are rendered...

here is a correct code:

```
<html>
<head>
  <meta charset="UTF-8">
  <script src="JsBarcode.code128.min.js"></script>
</head>
<body>
<p>Hi, this is normal text, below is barcode.</p>
<img id="barcode"/>
<script>
  var element = document.getElementById("barcode");
  JsBarcode(element, "Hi!");
</script>
</body>
</html>
```

Any way, your question is not related to the library. Close it.

**Comment by wilton323** [comment]
@SanichKotikov Thank you for your help!
