### ISSUE TITLE
Question: multiple barcodes

### ISSUE THREAD

**Issue by rajush** [lindell/JsBarcode#26]
This has been one of the best ones that i've found so far. I was able to display multiple barcodes by looping through, but I am not being able to show all the created barcodes in a canvas at once. Is there any better way for this to open the print dialogue once all the barcode have been generated, and display al the barcodes? Have been struggling to do this.

Any suggestions / steps would be greatly appreciated. Thanks.

**Comment by lindell** [comment]
What I would do is to fork this repo and change some things in the code of JsBarcode.js.

Specifically make [content](https://github.com/lindell/JsBarcode/blob/master/JsBarcode.js#L3) an array. Then just loop throw the content and create multiple barcodes with an added y-shift to the drawing of the [lines](https://github.com/lindell/JsBarcode/blob/master/JsBarcode.js#L103) and maybe the [text](https://github.com/lindell/JsBarcode/blob/master/JsBarcode.js#L79) if you want to use that as well.

**Comment by rajush** [comment]
Thanks... Actually looped through and kept passing the barcode to your function and kept attaching to the canvas did the trick. Didn't have to change anything to the source code.

**Comment by willos2006** [comment]
I'm Trying to do what you are doing, but my barcodes, despide the data changing each time, all apear the same

**Comment by moda20** [comment]
I am trying to do the same thing and my bar codes show up the same as the first one, I tried taking the canvas out of the loop so it's one canvas and jsBarCode just appends the data to it but to avail. 

Is there a fix or at lest a workaround using this library ?
