### ISSUE TITLE
GTIN/EAN

### ISSUE THREAD

**Issue by Marcellllll** [lindell/JsBarcode#260]
Hi,

I am sorry, I am a bit lost with all the formats. Is there any way to generate a GTIN/EAN barcode ? Specifically a GTIN-14 barcode (https://www.gtin.info/) ?

Kind regards,
Marcel

**Comment by SanichKotikov** [comment]
Hi,

> GTIN-14s may be encoded in ITF-14 or GS1-128 barcodes

Both formats are supported. Note, `GS1-128` is `CODE128` with `ean128: true` https://github.com/lindell/JsBarcode/wiki/CODE128#ean128-option-for-code128

**Comment by Marcellllll** [comment]
Thank you very much, this seems to be exactly what I needed !
