### ISSUE TITLE
Issues with Code128C

### ISSUE THREAD

**Issue by Zikaro** [lindell/JsBarcode#265]
So I'm actually using the vueJs wrapper library (vue-barcode) and have opened an issue there:
https://github.com/lindell/vue-barcode/issues/16

But it looked like it was just passing values directly so I suspect this might be an issue with this library instead. (see: https://code.amazon.com/packages/NodeJS-vue-barcode/blobs/vue-barcode-1.1.0/--/vue-barcode/index.js)

I have a UUID that I'm trying to generate a manageable barcode size for. A commonly suggested way is to use the hex representation then convert to decimal then use Code 128C to generate a barcode.

This library fails to generate barcodes using Code128C with any value of length greater than 20. At 20 it replaces the last couple digits with 0 so it's not even accurate unless you use a value <18 digits. Code128C does not have a length limitation... so it's unclear why this is happening. I can use online generators with no issues at all.

Example...
Input value (20 digit count): 12345678901234567890
The generate barcode:
[vue-barcode-issue-1.pdf](https://github.com/lindell/JsBarcode/files/2488301/vue-barcode-issue-1.pdf)

If you use the default format it reduces length by using scientific notation as a string and then generating a barcode against that string which doesn't even make sense.
[vue-barcode-issue-2.pdf](https://github.com/lindell/JsBarcode/files/2488302/vue-barcode-issue-2.pdf)

**Comment by SanichKotikov** [comment]
Looks like you're using a number instead of a string

**Comment by Zikaro** [comment]
Gotcha. That seems to have been it. Typing in JS is weird... cheers.
