### ISSUE TITLE
Uncaught Error: Not supported type to render on

### ISSUE THREAD

**Issue by lst94** [lindell/JsBarcode#274]
Hello,I have encountered such problem like following.
https://jsfiddle.net/hb9nr62q/1/
I dont't know where is wrong,plz help me,thanks!

**Comment by lst94** [comment]
https://jsfiddle.net/hb9nr62q/263/   this's correct url

**Comment by SanichKotikov** [comment]
@lst94 target element should be svg or canvas, but not a div.

**Comment by lst94** [comment]
I have solve it,but it's not the reason, still thanks to you!
