### ISSUE TITLE
Barcode scanning not working consistently

### ISSUE THREAD

**Issue by vaideesh07** [lindell/JsBarcode#276]
I am generating barcode on nodejs using jsbarcode and canvas. I am trying to scan using a barcode scanner app. The behaviour is inconsistent. Sometimes it gets scanned quickly whereas sometimes it takes a lot of time to scan. Can someone help me out with this ?

**Comment by lindell** [comment]
This has most likely nothing to do with this project. If the barcodes i correctly generated it is the fault of you scanner that you don't get a read. If you think there is something wrong with the generation, please provide an incorrectly generated barcode.

I will close the issue until then.
