### ISSUE TITLE
include the min version in the repo

### ISSUE THREAD

**Issue by justechn** [lindell/JsBarcode#28]
Can you include the minimized version (JsBarcode.all.min.js) in the repo so that when we install with bower we will have it?
Thanks

**Comment by fschaeffer** [comment]
+1 took me some time to notice the missing support for EAN when using bower and only including the provided JsBarcode.js

**Comment by lindell** [comment]
Was thinking of doing this or not. But now it's done.
https://github.com/lindell/JsBarcode/blob/master/JsBarcode.all.min.js
