### ISSUE TITLE
UPC barcode generation omitting first digit

### ISSUE THREAD

**Issue by Landcross** [lindell/JsBarcode#280]
I'm trying to use JsBarcode to generate some barcodes as they appear on the packaging. EAN13 works fine, but UPC barcodes don't quite match.

The example input I'm using is: 047875840614, which is formatted on the packaging as 0 47875 84061 4 as seen here:
![image](https://user-images.githubusercontent.com/12005521/52151938-fd586000-2674-11e9-844a-e67d37c16d38.png)

However, JsBarcode seems to omit the first digit and outputs the following:
![image](https://user-images.githubusercontent.com/12005521/52151963-0d703f80-2675-11e9-89d0-1b6ba2e989e6.png)

Now, I don't know very much about barcodes and there's probably a reason it's omitting the first 0, but I just want the barcodes to match visually. Any way to do that?

Thanks!

**Comment by SanichKotikov** [comment]
https://lindell.me/JsBarcode/generator/ works as expected

**Comment by Landcross** [comment]
Hmm, I found the problem. I had no "" around my barcode so it was probably interpreting the barcode as integer (and thus cutting the leading 0). My fault.

Sorry!
