### ISSUE TITLE
Como Criar o Modelo Interleaved 2 OF 5? (code-2of5)

### ISSUE THREAD

**Issue by Zimauro** [lindell/JsBarcode#285]
Para alguns padrões de documentos da Argentina precisamos gerar código de barras INTERLEAVED 2 OF 5 ou CODE-2OF5. Como implementar? Obrigado

**Comment by OllieStudio** [comment]
Hi! Having the same issue in Brazil:

"For some Argentine document standards we need to generate INTERLEAVED 2 OF 5 or CODE-2OF5 barcode. How to implement? Thanks"

**Comment by mateusfmello** [comment]
I have the same problem, Brazilian bills need the "Code-2of5 Interleaved" standard

**Comment by mateusfmello** [comment]
@ZZimmer71 @OllieStudio The "Code-2of5 Interleaved" format is represented with `ITF`

**Comment by edugemini** [comment]
You can use ITF-14
