### ISSUE TITLE
CODE128 generate incorrect barcode

### ISSUE THREAD

**Issue by kiwwi2019** [lindell/JsBarcode#293]
When I try to generate a CODE128 barcode for "720100016244413"  I got a bad barcode
 

https://lindell.me/JsBarcode/generator/
Data : 720100016244413

**I Obtain** :
![barcode_got](https://user-images.githubusercontent.com/49748599/56349225-a2380300-61b7-11e9-84a1-d4381ab7facd.png)

**Expected** : 
![barcode_expected](https://user-images.githubusercontent.com/49748599/56349969-3fe00200-61b9-11e9-806f-5ac3ca52fef3.png)

When I try to generate same barcode an other online generator I got the correct barcode

![barcode_got2](https://user-images.githubusercontent.com/49748599/56350076-71f16400-61b9-11e9-9f3d-21aae9310145.png)

![barcode_got3](https://user-images.githubusercontent.com/49748599/56350082-74ec5480-61b9-11e9-83a0-fd7a004f1971.gif)

**Comment by lindell** [comment]
Both are correct, but there seems to be difference in how jsbarcode and the generators you are using are doing the switch between CODE128C and A
