### ISSUE TITLE
Document SVG creation in Node

### ISSUE THREAD

**Issue by caesar** [lindell/JsBarcode#295]
I was struggling to create SVG barcodes in Node, and then I came across #149 and @lindell's comment https://github.com/lindell/JsBarcode/issues/149#issuecomment-300856699 which explains how to do it and contains a  helpful code snippet.

It would be great to document this in the README.

Happy to create a PR when I get time, unless there is a reason not to include this.

**Comment by lindell** [comment]
I've made a change in the readme with the example added :)

**Comment by caesar** [comment]
Fantastic! Thanks @lindell 👍
