### ISSUE TITLE
How to use it in react-native? is there way?

### ISSUE THREAD

**Issue by faustoct** [lindell/JsBarcode#301]

**Comment by marcferna** [comment]
Hey @faustoct, I think that https://www.npmjs.com/package/react-native-barcode-builder uses this for RN

**Comment by cdesch** [comment]
https://www.npmjs.com/package/react-native-barcode-builder  is broken with currently with issue [16](https://github.com/wonsikin/react-native-barcode-builder/issues/49) for `react-native >= 0.60`

**Comment by howadev** [comment]
You can use JsBarcode with Node.js to generate [SVG text](https://github.com/lindell/JsBarcode#with-svg) and pass it to [react-native-svg](https://github.com/react-native-community/react-native-svg#use-with-xml-strings) to render barcode.

**Comment by guiccbr** [comment]
For anyone that gets here, you can use something like this:

```
import { useMemo } from "react"

import JSBarcode from "jsbarcode"
import { SvgXml } from "react-native-svg"
import { DOMImplementation, XMLSerializer } from "xmldom"

interface Props {
  content: string
}

export const Barcode = ({ content }: Props) => {
  const svgText = useMemo(() => {
    const document = new DOMImplementation().createDocument(null, "html")
    const svgNode = document.createElementNS(null, "svg")

    JSBarcode(svgNode, content, { xmlDocument: document })

    // Removing some attributes are not supported by react-native-svg. Those
    // should not affect the rendering in our use case.
    svgNode.removeAttribute("style")

    return new XMLSerializer().serializeToString(svgNode)
  }, [content])

  return <SvgXml xml={svgText} />
}
```
