### ISSUE TITLE
"Not supported type to render on" on SVG, but not on CANVAS, and IMG

### ISSUE THREAD

**Issue by zorgoz** [lindell/JsBarcode#303]
I am creating elements to be turned into barcode with jquery. It works with CANVAS and IMG, but with SVG I am getting `InvalidElementException: Not supported type to render on`. It makes no difference if I try to apply JsBarcode at any time after the elements were rendered. But if I copy-paste the rendered html code, it works. I tried both with `prop` and `attr`.

```
let data = ["2200010000207","2200011000305","2200012000403","2200013000501","2200014000609","2200024000705","9100300040001"]

let $table = $('table')

for(let item of data){
		let $td = 
				$('<td>').append($('<svg>').addClass('barcode')
							.attr('jsbarcode-value',item)
							.attr('jsbarcode-format','ean13')
							.attr('jsbarcode-height',25)
							.attr('jsbarcode-displayvalue','true')
							.attr('jsbarcode-margin','5')
							)
				$table.append($('<tr>').append($td))
}

JsBarcode('.barcode').init()
```

[demo on CodePen](https://codepen.io/zorgoz/pen/gOYxrWW)

**Comment by lindell** [comment]
SVG element is a bit special and needs to be created with `document.createElementNS` instead of `document.createElement`.

This seems to be someone using it with jQuery https://jsfiddle.net/bjelline/8VNqt/

**Comment by zorgoz** [comment]
Nope. The sample you have posted creates elements inside SVG, not the SVG itself. I have updated my [pen](https://codepen.io/zorgoz/pen/gOYxrWW?editors=1010), to use `document.createElementNS`, but makes no difference.

**Comment by zorgoz** [comment]
Thank you, it works!

Here is the updated code just to be available for anybody else:

```
let data = ["2200010000207","2200011000305","2200012000403","2200013000501","2200014000609","2200024000705","9100300040001"]

let $table = $('table')

for(let item of data){
    let $el = $(document.createElementNS('http://www.w3.org/2000/svg','svg'))
    $el.addClass('barcode')
				.attr('jsbarcode-value',item)
				.attr('jsbarcode-format','ean13')
		let $td = $('<td>').append($el)
    
    $table.append($('<tr>').append($td)) 
}

JsBarcode('.barcode').init()
```
