### ISSUE TITLE
Type definitions for option.xmlDocument

### ISSUE THREAD

**Issue by davps** [lindell/JsBarcode#311]
There is no Typescript's type definition for `xmlDocument`, which is a valid option when we use JsBarcode with nodejs and the svg output. 

Also, it's not listed on the Options wiki:
https://github.com/lindell/JsBarcode/wiki/Options

Tested with  jsbarcode 3.11.0

**Comment by silverio** [comment]
I am having the same issue. Is there a fix coming soon? or any work around?
