### ISSUE TITLE
Please add One More field to ADD SKU name on the above of Barcode

### ISSUE THREAD

**Issue by shivank44** [lindell/JsBarcode#319]
@lindell @SanichKotikov 
I have to generate UPC code with SKU Name Above of image 
Please see the below sample image.
![upccodewithsku](https://user-images.githubusercontent.com/52524465/68848646-a3ea8a80-06f6-11ea-8486-e72cc5ab98db.png)

**Comment by karelbyte** [comment]
@shivank44 Hi friend, did you manage to put the text on the bar code?

**Comment by shivank44** [comment]
Yes I can help you.

**Comment by shivank44** [comment]
**Currently I create a div and pass SKU text in h1 tag and below it we add img tag to show barcode.
And use html2canvas library to generate required result.**
**My code in PHP is** 

                    <h1 <?php if(empty($variant['sku'])){ echo 'style="display:none;"'; } else { 'style="text-align: center;"'; }?>>SKU: <?php echo $variant['sku'];?></h1>
                     
                    <div id="barcodeimagediv<?php echo $variant['id'];?>" <?php if(!empty($variant['upc_code'])){ echo 'style="border-style: solid; background-color: white; text-align: center;display: inline-block;vertical-align: top;"'; }?>>
                    <h3 style="text-align: center;<?php if(empty($variant['upc_code'])){ echo 'display:none;';}?>"><?php if(!empty($variant['sku'])){ echo "SKU:".$variant['sku'];}?></h3>
                    <img id="barcode<?php echo $variant['id'];?>" width="100%" />
                    </div>
                    <a class="btn btn-info show_barcode" variant_id="<?php echo $variant['id'];?>" <?php if(empty($variant['upc_code'])){ echo 'style="display:none;"'; }?> target="_blank">Download UPC Image</a>
                              
                    <script>
                        <?php if(!empty($variant['upc_code'])){?>
                            try{
                                JsBarcode("#barcode<?php echo $variant['id'];?>", "<?php echo $variant['upc_code'];?>", 
                                {
                                    format: "UPC",
                                    font: "helvetica",
                                    fontOptions: "bold",
                                    fontSize: "60",
                                    width: "6",
                                    height: "200",
                                    valid: function(valid){
                                        if(!valid){
                                        alert("Please enter a valid UPC code");
                                        return false;
                                        }
                                    },
                                });
                            }catch(UPC){
                                alert(UPC);
                            }
                            <?php } ?> 
                    </script>

**for download UPC code**
<script>
                    const clearUrl = url => url.replace(/^data:image\/\w+;base64,/, '');
                    const downloadImage = (name, content, type) => {
                  var link = document.createElement('a');
                  link.style = 'position: fixed; left -10000px;';
                  link.href = `data:application/octet-stream;base64,${encodeURIComponent(content)}`;
                  link.download = /\.\w+/.test(name) ? name : `${name}.${type}`;

                  document.body.appendChild(link);
                  link.click();
                  document.body.removeChild(link);
                }

$('body').on('click','.show_barcode',function(){
                        var variant_id=$(this).attr('variant_id');
                        var upc_code = $("#upc_code"+variant_id).val();
                        var g = document.createElement('div');
                            g.setAttribute("id", "img1");
                            g.style = 'position: fixed;font-family: "helvetica";';
                            document.body.appendChild(g);
                            
                            $("#barcodeimagediv"+variant_id).css("width","750px");
                            $("#barcodeimagediv"+variant_id).find("h3").css("font-size","50px");
                            
                            html2canvas(document.getElementById("barcodeimagediv"+variant_id), {
                                onrendered: function(canvas) {
                                  canvas.className = "html2canvas";
                                  
                                  $("#barcodeimagediv"+variant_id).css("width","auto");
                                  $("#barcodeimagediv"+variant_id).find("h3").css("font-size","24px");
                                  
                                  var ctx = canvas.getContext('2d');

                                ctx.webkitImageSmoothingEnabled = false;
                                ctx.mozImageSmoothingEnabled = false;
                                ctx.imageSmoothingEnabled = false;
                                  
                                  document.getElementById("img1").appendChild(canvas);
                                  var image = canvas.toDataURL("image/png");
                                  downloadImage("UPC"+variant_id, clearUrl(image), 'png');
                                },
                                useCORS: true
                          });
                       
                    });
                    </script>

**html2canvas library**
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.min.js"></script>
