### ISSUE TITLE
add code 128 GS1

### ISSUE THREAD

**Issue by Nickolyashka** [lindell/JsBarcode#324]

**Comment by ace68723** [comment]
GS1-128 is a subset of Code 128. You can use ```\xCF``` as ```FNC1```

```
JsBarcode("#GS1-128", "\xCF010692180470156317210511\xCF1021AD", {
  format: "CODE128",
});
```

**Comment by SanichKotikov** [comment]
@Nickolyashka https://github.com/lindell/JsBarcode/wiki/CODE128#ean128-option-for-code128
