### ISSUE TITLE
window.jQuery

### ISSUE THREAD

**Issue by barchard** [lindell/JsBarcode#33]
It [looks like](https://github.com/lindell/JsBarcode/blob/master/JsBarcode.js#L151) this is tied to `window.jQuery`. Is there a reason why? From the plugin boilerplates [here](https://css-tricks.com/snippets/jquery/jquery-plugin-template/) and [here](https://github.com/jquery-boilerplate/jquery-boilerplate/blob/master/dist/jquery.boilerplate.js) pass in and use a jQuery object. Changing `window.jQuery` to just `jQuery` worked for me. I would think, if someone had used `noConflict`, that they'd run into issues.

**Comment by lindell** [comment]
It was just jQuery before. The change was done in commit 43f3f64bf9388655e7e2ebb97f0337581bcddbe5 by @bcho. Why is that change made @bcho?

**Comment by bcho** [comment]
@lindell Sorry, can't recall why (maybe some issues on using this scripts without jquery), but can we remove all `window.jQuery` inside the body with `jQuery`?

**Comment by lindell** [comment]
It should be that ```$===jQuery===windows.jQuery``` and that the ```
(function($){CODE})(jQuery);``` is only done to ensure that $ is not in conflict with any other library. I do some tests and cleanup in the next couple of days.

**Comment by bcho** [comment]
@lindell :+1:

**Comment by lindell** [comment]
83d0f8b62a9e1b6424ca051c3337f8384963376b seems to work fine. Not pushing it to main branch before some testing but should be the exact same thing.

**Comment by lindell** [comment]
Now pushed to main
