### ISSUE TITLE
when i set the margin again my canvas/svg gets wrong width

### ISSUE THREAD

**Issue by ZhiiChong** [lindell/JsBarcode#331]
It's very nice of you to create this library, but I meet a problem that when I set the margin over again by HTML widget, the canvas/svg gets wrong width by plus barcode's width(150px e.g.) with margin(10px e.g.) as strings. And the result canvas's width is like 1501010 px. However if I just change the default margin instead of changing it as an attribute, it works. It works without any problems when I change other attributes using HTML widget. 

My HTML is like:
``` html
<input id="bar-margin" class="option-range" type="range" name="bar-margin" value="10" min="0" max="25" oninput="barMargin()">
```
My JavaScript is like:
``` javascript
var barOptions = {
    //format: "CODE128",
    width: 2,
    height: 100,
    margin: 0,
    // color
    background: "#ffffff",
    lineColor: "#000000",
    // font/text options
    displayValue: true,
    // text: undefined,
    fontOptions: "",
    font: "monospace",
    textAlign: "center",
    textPosition: "bottom",
    textMargin: 2,
    fontSize: 20,
    valid: 
        function(valid) {
            if(valid) {
                console.log("barcode generated!");
            }
            else {
                console.log("not valid data for barcode!")
            }
        }
};

function barGen() {
    barCanvasClear();
    JsBarcode(barCanvas, inputText, barOptions);
}

function barCanvasClear() {
    var barCanvas = document.getElementById("bar-canvas");
    /*barCanvas.getContext("2d").clearRect(0,0,barCanvas.width,barCanvas.height);     
Another problem: clearRect() doesn't work to clear barCode's canvas.*/
    barCanvas.height = 0;  
    barCanvas.width = 0;
    if(isCanvasBlank(barCanvas)){
        console.log("barCanvas clear!");
    }
    else{
        console.log("barCanvas not clear!");
    }
}

function barMargin() {
    var margin = document.getElementById("bar-margin").value;
    var marginValue = document.getElementById("bar-margin-value");
    barOptions.margin = margin;
    marginValue.innerHTML = margin;
}
```

Could you please give some solutions?

**Comment by lindell** [comment]
![image](https://user-images.githubusercontent.com/284868/78367503-7e392180-75c2-11ea-87ea-69f44273d6d4.png)
The should be a number.

**Comment by ZhiiChong** [comment]
> ![image](https://user-images.githubusercontent.com/284868/78367503-7e392180-75c2-11ea-87ea-69f44273d6d4.png)
> The should be a number.

Well thanks. I use `parseInt()` and then the problem is solved.
 
But weirdly, I place the slider to the minimum and find the result in console. Then I get `margin: 0` instead of `margin: "0"`.
