### ISSUE TITLE
barcode + text

### ISSUE THREAD

**Issue by nunob87** [lindell/JsBarcode#332]
hello, I can't have a barcode and a text underneath ??

thanks

**Comment by lindell** [comment]
Please provide more information of what your problem is with a reproducible example and reopen this issue in that case :)

**Comment by nunob87** [comment]
I want to print the label with the barcode, the product name and the price, and to control the size of the printing label, on the barcode part ok

example vue js
<barcode tag="svg" :value="123456789" text="teste"></barcode>
