### ISSUE TITLE
Can you please update versions for lindell.me?

### ISSUE THREAD

**Issue by ndorofeeva** [lindell/JsBarcode#333]

**Comment by ndorofeeva** [comment]
Spent a lot of time investigating why ean128 not working, then realised that https://lindell.me/JsBarcode/#download has links to old versions.
Already downloaded latest from github but please spare time for others and update the links

**Comment by lindell** [comment]
Jsdelivr (the CDN used) updated to only look at npm versions a while back. I now fixed to use that new API instead and the newest version is shown on the site. https://lindell.me/JsBarcode/#download

**Comment by AbdeenM** [comment]
The links broke again.
For anyone that lands here, i resolved it by replacing the CDN links with `https://unpkg.com`. i.e.:
`https://unpkg.com/jsbarcode@3.11.5/dist/barcodes/JsBarcode.code128.min.js`
