### ISSUE TITLE
nodejs - jsbarcode - image generate different in docker container and in local

### ISSUE THREAD

**Issue by dev080** [lindell/JsBarcode#334]
I'm realizing barre code based on doctor rpps in France. This just a eleven number code.

"canvas": "^2.6.1",
"jsbarcode": "^3.11.0",

In local the image is perfect.

![codeBarre](https://user-images.githubusercontent.com/16777498/83261509-c0926f80-a1bb-11ea-9f3c-ab163733e508.png)

Under docker :

![codeBarre-issue](https://user-images.githubusercontent.com/16777498/83261625-ecadf080-a1bb-11ea-865d-8c78e8c9a7fe.png)

Need help to understand

**Comment by lindell** [comment]
Does the docker image have any monospace fonts installed?
