### ISSUE TITLE
Text is blurred

### ISSUE THREAD

**Issue by kikyoluka** [lindell/JsBarcode#335]
When I use the plugin to design a barcode and print it, the text of the barcode is blurred, even if I modify the font.

Is there any way to make it clearer?  
Thanks

**Comment by lindell** [comment]
Have you tried using svg?

**Comment by kikyoluka** [comment]
> 您是否尝试过使用svg？

The canvas I use has not tried svg, but I will try it today, thank you for your suggestion

**Comment by kikyoluka** [comment]
> 您是否尝试过使用svg？

Thanks, I solved this problem after using svg
