### ISSUE TITLE
Code 128 ASCII barcodes

### ISSUE THREAD

**Issue by tjunussovbee** [lindell/JsBarcode#34]
Hi! Great feature, Is it possible to generate non-text ASCII characters such as ESC,TAB,DEL etc ?
Like in [here http://stackoverflow.com/questions/30895388/tab-key-in-code128-barcodes](http://stackoverflow.com/questions/30895388/tab-key-in-code128-barcodes)
says...

In supporting barcode symbologies, when the parse option is specified, any instances of ^NNN in the data field are replaced with their equivalent ASCII value, useful for specifying unprintable characters.

**Comment by lindell** [comment]
The latest release supports CODE128A, this means you could use the special characters. It does not and will probably never support the parsing with ^NNN but you could do this yourself with not to much problem.

You can use it by:
````javascript
  JsBarcode("#barcode", "HELLO" + String.fromCharCode(9) + "WORLD"); //HELLO[TAB]WORLD
````

Automatic switching between the A,B and C mode is comming but not implemented just yet
