### ISSUE TITLE
Save to file?

### ISSUE THREAD

**Issue by andreyxc** [lindell/JsBarcode#341]
Tell me how to save the result to a file ?

**Comment by lindell** [comment]
It depends if you want to use canvas (png/etc.) or svg.

With canvas.
```js
const buffer = canvas.toBuffer('image/png');
fs.writeFileSync('./test.png', buffer);
```

Just save the generated svg string to a file.
```js
fs.writeFileSync('./test.svg', svgText);
```

(You should probably use the not sync version if this is not in a single run script)
