### ISSUE TITLE
Tab key not working

### ISSUE THREAD

**Issue by lordkittygeek** [lindell/JsBarcode#343]
In order to use the tab key in your generator, I have to type in ~009, sadly it doesn't convert it to tab key and takes it as an ordinary string. The following site does the trick, can you please include in your library some sort of escape characters or special ones, ~009 should be a tab button, not an ordinary string.

https://www.bcgen.com/linear-barcode-creator.html

**Comment by lindell** [comment]
Does `JsBarcode("#barcode", "\t");` work?

**Comment by lordkittygeek** [comment]
It does work if you will use it in the following format, but I have web app that takes input value from user and my code looks like this:
JsBarcode("#barcode", test, {
  format: "CODE128",
  lineColor: "#000000",
  width: 1.3,
  height: 25,
  displayValue: true,
  fontSize: 11
});
Problem is that if  I will type in input something like this username\tpassword, it won't work properly.

**Comment by lindell** [comment]
No, JsBarcode does not and will never automatically escape things for you since that may limit if you actually want to do that encoding.

But if you for example want the first example, you can easily just convert it before generating the barcode.

```js
const textToGenerate = userInput.replace(/~[0-9]{3}/, function (x) {
  return String.fromCharCode(x.substr(1));
});
```
