### ISSUE TITLE
Proposal: Auto calculate checksums

### ISSUE THREAD

**Issue by barchard** [lindell/JsBarcode#35]
What are your thoughts on auto-calculating the Checksums for barcodes that support this and appending it to the value? For instance, when using UPC, if the length is 12 characters, automatically calculating and appending the checksum digit to the end of the number?

**Comment by lindell** [comment]
This is now done with the latest release. Working for EAN13, EAN8 and UPC

**Comment by barchard** [comment]
:+1:
