### ISSUE TITLE
All barcodes are not generated in query while loop

### ISSUE THREAD

**Issue by masimies** [lindell/JsBarcode#356]
HI,
I'm testing my site for PHP8 update. Old barcode generator was not working anymore and i found JsBarcode for replacement because it was simple to implement for me also. :-)
I found one combination what was partially working with my PHP-code.

In while loop i need firstname and lastname from table:
`<svg id="barcode" jsbarcode-value="'.$firstname.' '.$lastname.'" jsbarcode-width="1" jsbarcode-height="30" jsbarcode-margin="5" jsbarcode-displayValue="false"></svg>`

And in script:
`<script>JsBarcode("#barcode").init();</script>`

Barcodes are generated correctly. But only 3,4 or 6 of them only from beginning. All others are blank.
I assume that i have problem with correct syntax in script. Or JsBarcode does not work in loop.

Am i doing this with totally wrong way? :-)

**Comment by lindell** [comment]
Can you please provide the generated HTML code that PHP is generating

**Comment by masimies** [comment]
Due the sensitive data i took a partial snapshot from generated code. It shows that HTML code is generated with whole query result, but barcodes are not visible in all of them. Is this helping for analysing issue? I tried also unloading other plugins also. This is very clean installation of my wordpress sandbox environment. So there should not be any "old"-stuff under.

`<fieldset class="dish" style="width:380px; height:150px; margin-top:10px; margin-left:10px; border:1px solid #009041;">
<legend class="dish">
<img src="./assets/img//hslogo50.png"/>user 1</legend>
<center>
<svg id="barcode" jsbarcode-value="user 1" jsbarcode-width="1" jsbarcode-height="30" jsbarcode-margin="5" jsbarcode-displayValue="false"></svg>
<label class="h5" style="padding:2px; margin:0px;">School1 2020 - 2021</label>
<label class="h5" style="padding:2px; margin-top:0px; font-size:0.8em; color:#009041; vertical-align:top;"><i class="fa fa-taxi" aria-hidden="true" style="color:red; font-size:1.2em; vertical-align:top;"></i>R01A R16B R01C<i class="fa fa-home" aria-hidden="true" style="color:#009041; font-size:1.2em; margin-left:5px; vertical-align:top;"></i>Class 1<i class="fa fa-user" aria-hidden="true" style="color:#009041; font-size:1.2em; margin-left:5px; vertical-align:top;"></i>190321115902</label></center>
</fieldset><fieldset class="dish" style="width:380px; height:150px; margin-top:10px; margin-left:10px; border:1px solid #009041;">
<legend class="dish">
<img src="./assets/img//hslogo50.png"/>user 2</legend>
<center>
<svg id="barcode" jsbarcode-value="user 2" jsbarcode-width="1" jsbarcode-height="30" jsbarcode-margin="5" jsbarcode-displayValue="false"></svg>
<label class="h5" style="padding:2px; margin:0px;">School1 2020 - 2021</label>
<label class="h5" style="padding:2px; margin-top:0px; font-size:0.8em; color:#009041; vertical-align:top;"><i class="fa fa-taxi" aria-hidden="true" style="color:red; font-size:1.2em; vertical-align:top;"></i>R01A R09B R01C<i class="fa fa-home" aria-hidden="true" style="color:#009041; font-size:1.2em; margin-left:5px; vertical-align:top;"></i>Class 1<i class="fa fa-user" aria-hidden="true" style="color:#009041; font-size:1.2em; margin-left:5px; vertical-align:top;"></i>190522053420</label></center>
</fieldset><fieldset class="dish" style="width:380px; height:150px; margin-top:10px; margin-left:10px; border:1px solid #009041;">
<legend class="dish">
<img src="./assets/img//hslogo50.png"/>user 3</legend>
<center>
<svg id="barcode" jsbarcode-value="user 3" jsbarcode-width="1" jsbarcode-height="30" jsbarcode-margin="5" jsbarcode-displayValue="false"></svg>
<label class="h5" style="padding:2px; margin:0px;">School1 2020 - 2021</label>
<label class="h5" style="padding:2px; margin-top:0px; font-size:0.8em; color:#009041; vertical-align:top;"><i class="fa fa-taxi" aria-hidden="true" style="color:red; font-size:1.2em; vertical-align:top;"></i>R01A R09B <i class="fa fa-home" aria-hidden="true" style="color:#009041; font-size:1.2em; margin-left:5px; vertical-align:top;"></i>Class 1<i class="fa fa-user" aria-hidden="true" style="color:#009041; font-size:1.2em; margin-left:5px; vertical-align:top;"></i>190522054007</label></center>
</fieldset><fieldset class="dish" style="width:380px; height:150px; margin-top:10px; margin-left:10px; border:1px solid #009041;">
<legend class="dish">
<img src="./assets/img//hslogo50.png"/>user 4</legend>
<center>
<svg id="barcode" jsbarcode-value="user 4" jsbarcode-width="1" jsbarcode-height="30" jsbarcode-margin="5" jsbarcode-displayValue="false"></svg>
<label class="h5" style="padding:2px; margin:0px;">School1 2020 - 2021</label>
<label class="h5" style="padding:2px; margin-top:0px; font-size:0.8em; color:#009041; vertical-align:top;"><i class="fa fa-taxi" aria-hidden="true" style="color:red; font-size:1.2em; vertical-align:top;"></i>R09A R16B <i class="fa fa-home" aria-hidden="true" style="color:#009041; font-size:1.2em; margin-left:5px; vertical-align:top;"></i>Class 1<i class="fa fa-user" aria-hidden="true" style="color:#009041; font-size:1.2em; margin-left:5px; vertical-align:top;"></i>190715063112</label></center>
</fieldset><fieldset class="dish" style="width:380px; height:150px; margin-top:10px; margin-left:10px; border:1px solid #009041;">
<legend class="dish">
<img src="./assets/img//hslogo50.png"/>user 5</legend>
<center>
<svg id="barcode" jsbarcode-value="user 5" jsbarcode-width="1" jsbarcode-height="30" jsbarcode-margin="5" jsbarcode-displayValue="false"></svg>
<label class="h5" style="padding:2px; margin:0px;">School1 2020 - 2021</label>
<label class="h5" style="padding:2px; margin-top:0px; font-size:0.8em; color:#009041; vertical-align:top;"><i class="fa fa-taxi" aria-hidden="true" style="color:red; font-size:1.2em; vertical-align:top;"></i>R09A  <i class="fa fa-home" aria-hidden="true" style="color:#009041; font-size:1.2em; margin-left:5px; vertical-align:top;"></i>Class 1<i class="fa fa-user" aria-hidden="true" style="color:#009041; font-size:1.2em; margin-left:5px; vertical-align:top;"></i>190812074458</label></center>
</fieldset><fieldset class="dish" style="width:380px; height:150px; margin-top:10px; margin-left:10px; border:1px solid #009041;">
<legend class="dish">
<img src="./assets/img//hslogo50.png"/>user 6</legend>
<center>
<svg id="barcode" jsbarcode-value="user 6" jsbarcode-width="1" jsbarcode-height="30" jsbarcode-margin="5" jsbarcode-displayValue="false"></svg>
<label class="h5" style="padding:2px; margin:0px;">School1 2020 - 2021</label>
<label class="h5" style="padding:2px; margin-top:0px; font-size:0.8em; color:#009041; vertical-align:top;"><i class="fa fa-taxi" aria-hidden="true" style="color:red; font-size:1.2em; vertical-align:top;"></i>R05A R09B <i class="fa fa-home" aria-hidden="true" style="color:#009041; font-size:1.2em; margin-left:5px; vertical-align:top;"></i>Class 1<i class="fa fa-user" aria-hidden="true" style="color:#009041; font-size:1.2em; margin-left:5px; vertical-align:top;"></i>200303071007</label></center>
</fieldset><fieldset class="dish" style="width:380px; height:150px; margin-top:10px; margin-left:10px; border:1px solid #009041;">
<legend class="dish">
<img src="./assets/img//hslogo50.png"/>user 7</legend>
<center>
<svg id="barcode" jsbarcode-value="user 7" jsbarcode-width="1" jsbarcode-height="30" jsbarcode-margin="5" jsbarcode-displayValue="false"></svg>
<label class="h5" style="padding:2px; margin:0px;">School1 2020 - 2021</label>
<label class="h5" style="padding:2px; margin-top:0px; font-size:0.8em; color:#009041; vertical-align:top;"><i class="fa fa-taxi" aria-hidden="true" style="color:red; font-size:1.2em; vertical-align:top;"></i>R01A  <i class="fa fa-home" aria-hidden="true" style="color:#009041; font-size:1.2em; margin-left:5px; vertical-align:top;"></i>Class 1<i class="fa fa-user" aria-hidden="true" style="color:#009041; font-size:1.2em; margin-left:5px; vertical-align:top;"></i>200807114643</label></center>
</fieldset>`

**Comment by lindell** [comment]
Seems to be working just fine

https://jsfiddle.net/svyq6df7/2/

One note, you are using ids as identifiers. IDs are meant to be unique per webpage. It seems to work either way, but it's not actually compliant with html/js specs.

**Comment by masimies** [comment]
Found the issue fault. It's our "Finnish" characters. ä and others, like ö :-D
Barcode generation stops if there is that kind of letters in values.

**Comment by masimies** [comment]
Tried to find a way for covert these letters like in case of name is Mäenpää.
No matter what i have used. In database value Ã¤, UTF-8 Value:0xC4, or HTML Entity:&#196; for the ä, it does not accept it for barcode. JsBarcode generates values as they are presented in string and do not handle any special letters. I think that only way to complete this is, convert ä to a before barcode-value.

**Comment by lindell** [comment]
[CODE128](https://en.wikipedia.org/wiki/Code_128) or any other supported barcode does not support "special characters" like `å`, `ä` or `ö`. This is the barcode specification and another that JsBarcode can do anything about, unfortunately

Converting `å` and `ä` to `a` and `ö` to `o` is a workaround that might work for you.
