### ISSUE TITLE
Not working with EAN format.

### ISSUE THREAD

**Issue by nmnandakishore** [lindell/JsBarcode#36]
Doesn't display any error. But no output.

**Comment by lindell** [comment]
What input did you use? No other reports of EAN not working.

**Comment by nmnandakishore** [comment]
It was an EAN input without prefix. I even tried with prefix, But didn't work.

**Comment by lindell** [comment]
Can you give any code that you used? Did you get any javascript errors? Did it work with any other barcode?

**Comment by nmnandakishore** [comment]
It worked with code128. And sorry, I don't have the code now. I used some other library. If you wish, I can reproduce in my free time :)

**Comment by lindell** [comment]
That would be great, even necessary for me to take a look at this :)

**Comment by lindell** [comment]
Since I don't get any feedback for what could be wrong (since it seems to be working) I close this issue until indications of any problem.

**Comment by hpabubacar** [comment]
doesnt work on my code either. 

my code for the display is svg. and jscript code is like this:
`<script>
							$(document).ready(function(){
    						$("#gen").click(function(){
			        		JsBarcode("#barcode", $('#barc').val())
    						});
    						$("#gen").click(function(){
        					$("#printu").show();
    						});
						});
						$(document).keypress(function(e){
							if(e.which == 13){
								JsBarcode("#barcode", $('#barc').val(), {format: "EAN13"});
							}
						});
					</script>`

does it have anything to do with the size of the printout?
