### ISSUE TITLE
Encode FNC3 endcode

### ISSUE THREAD

**Issue by benford14** [lindell/JsBarcode#361]
Hello! I was looking for assistance creating a 128 code barcode with a trailing fnc3. I was instructed to use a bar code generator using 128 code format (symbology, if I'm using that correct), and have BT_ADR############.fnc3 as the characters where the #s are the mac/serial of a unit. When I use that under a normal barcode generator it will not work. In doing some research it appears there's a way to encode that fnc3? Is there anyone that could help me create that bar code properly?

**Comment by lindell** [comment]
`"\x60"` is fnc3 https://en.wikipedia.org/wiki/Code_128

`"BT_ADR############.\x60"`

**Comment by benford14** [comment]
@lindell Thank you! I tried this and it didn't work properly. I'm getting some contradicting information. They company I'm working with said to use .fnc3 (hex30) which doesn't add up based on what you linked me. It appears fnc3 is /60, so I'm wondering what it really should be. I have the working barcode, maybe this would help figure out what exactly I need to enter into a random barcode generator to reproduce?

![Barcode](https://user-images.githubusercontent.com/79476309/108870069-c93a9980-75c5-11eb-865b-bc2009724904.png)

**Comment by lindell** [comment]
Hello again, I was wrong about `\x60`. That is the internal representation. You need to look at locking the code128 code to one of the modes (b for example). And then use the representation in the "code" column. 

Like this:
```
JsBarcode("#code128", "BT_ADR1804EDF104FF.\xC9", {format: "code128b", width: 1});
```

This does not result in the exact same barcode as yours, but there is a lot of ways of generating code128 codes, like shifting between the different modes etc. I will not be able to help you in trying to find out exactly which modes and which switches your barcode example is using, but the snippet above should provide a valid code to your spec.

**Comment by benford14** [comment]
Thanks for the help @lindell I really appreciate it. I'm way into the programming of barcodes and I'm very unfamiliar. I cannot seem to figure out how to recreate this barcode but I learned how a lot works and that somehow I need to encode this fnc3 trailer.  Thanks again!
