### ISSUE TITLE
I need to create a horizontal bar code

### ISSUE THREAD

**Issue by MarcoCasanovaPepiln** [lindell/JsBarcode#364]
Can I use JsBarcode?

thanks

**Comment by lindell** [comment]
Yes, all barcodes generated by jsbarcode are horizontal

**Comment by MarcoCasanovaPepiln** [comment]
I need one vertical :(

Thanks

**Comment by lindell** [comment]
Jsbarcode does not (and will not) support the rendering om vertical barcodes. But depending on the use case, you can easily rotate, for example the html element that is the barcode. Googöe is your friend here

**Comment by MarcoCasanovaPepiln** [comment]
Thank you for the clarification.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
