### ISSUE TITLE
JsBarcode.all.min.js bug

### ISSUE THREAD

**Issue by lollita** [lindell/JsBarcode#368]
JsBarcode("#barcode", "Example1234");
not work with
JsBarcode.all.min.js
but work with
JsBarcode.all.js

SyntaxError: invalid range in character class  JsBarcode.all.min.js:2:25055

**Comment by lindell** [comment]
Make sure that your encoding is set correctly :)

**Comment by lollita** [comment]
Ensure you test my example:
this work:
`<svg id="barcode" />
<script src="JsBarcode.all.js"></script>
<script>
var a=JsBarcode("#barcode", "Example1234");
</script>`

**Comment by lindell** [comment]
Working just fine with a correctly encoded version:
![image](https://user-images.githubusercontent.com/284868/118841431-9a804680-b8c8-11eb-950f-346ff972a073.png)
https://jsfiddle.net/z35cbjdn/

**Comment by lollita** [comment]
Ok, I now see that this is the problem.
On a old browser have to encode.
ty.
