### ISSUE TITLE
width & height

### ISSUE THREAD

**Issue by FabrizioReitano** [lindell/JsBarcode#369]
Hi,
i have some problem specifing the image size. For example:

- with height=320 and width=1 the library produces a 398hX422w png image. 
- with height=320 and width=2 the library produces a 398hX298w png image. 
- with height=320 and width=3 the library produces a 398hX422w png image. 

How can i predict the size of the resulting image? Width and Height parameters are not in pixel?

**Comment by lindell** [comment]
width=1 and width=3 producing the same with sounds very strange. Can you please provide an example?

The height is the height of the barcode, then there are margins + text as well.

**Comment by FabrizioReitano** [comment]
That's an example of CODE128B png image

![test](https://user-images.githubusercontent.com/2396006/118831420-0dd18a80-b8c0-11eb-8883-16558f1c2013.png)

and that's the code I used to generate it:

```
const canvas = new Canvas(2, 100, 'png');
JsBarcode(canvas, 'Test_123', {
    format: 'CODE128B',
    width: 1,
    height: 320,
    displayValue: false
});
```

The size with borders is 376hX389w, without borders is 355hX370w

**Comment by lindell** [comment]
```js
const fs = require("fs");
const JsBarcode = require("jsbarcode");
const { createCanvas } = require("canvas");

const canvas = createCanvas();
JsBarcode(canvas, "Test_123", {
  format: "CODE128B",
  width: 1,
  height: 320,
  displayValue: false,
});

const stream = canvas.createPNGStream();
const out = fs.createWriteStream(__dirname + "/test.png");
stream.pipe(out);
```

generates this file:
![test](https://user-images.githubusercontent.com/284868/118835668-7e2ddb00-b8c3-11eb-8800-51d2e0109512.png)

That is 142 x 340, exactly as expected (320 + 10 over + 10 under).
