### ISSUE TITLE
JsBarcode does not gets scanned after converting it with the help ofclj-htmltopdf pdf but works in html, my requirement is for PDF

### ISSUE THREAD

**Issue by amandhaasil** [lindell/JsBarcode#376]
I used the example, and it worked on the HTML, but when converting to PDF does not. I saw that some other people have the same problem with other Html->pdf converters.  I'm using the clj-htmltopdf to render the pdf. Maybe just an example on how to go around this issue would be great, maybe using canvas...

Example that did not work?
```
<script>
        function generateBarcode() {
            let configuracao = {
                width: 1.5,
                height: 70,
                displayValue: true
            };
            JsBarcode('#codBarras', "3409589485769687", configuracao);
        }
</script>

<svg id="codBarras"></svg>
```
I tried adding the function to onload of the body. Tried calling the  JsBarcode('#codBarras', "3409589485769687", configuracao); directly instead of inside a function...many other but nothing

**Comment by lindell** [comment]
I'm sorry, but if the barcode works but not when converted. The problem is in the conversion and not in this library. If you find a good way of working with a specific pdf library, please add a page to the wiki 🙂 But any official documentation for any specific library will not be added.
