### ISSUE TITLE
Image Resolution

### ISSUE THREAD

**Issue by SivaRamRIT** [lindell/JsBarcode#38]
Hi, is there any way to increase the quality of the generated barcode image like upto 640px. The barcode image is not getting recognized in a barcode reader( like QuaggaJS).

**Comment by lindell** [comment]
You could just increase. the Width to something like 5-10 depending on the lines and height to the exact height you want to have.

But it should not be needed. Either it's a bug in the generation or QuaggaJS is bad at recognizing.
