### ISSUE TITLE
Creating Pop up window to print barcode

### ISSUE THREAD

**Issue by mcpalmer1328** [lindell/JsBarcode#382]
so the barcodes work fine and print fine, but what i am trying to do it have a pop up show up with the barcode so that i can have people just print the barcode without everything else on the screen...thought.  the way i used to do it with js is below (obvious with a different barcode program that did not print very well.

var first = '';
			var second = '';
			var sku2 = $('#Special').val();
			var quantity = $('#SPquantity').val();
			var indexGlobal = 0;
						for (x=0;x<quantity;x++)
					{
						JsBarcode("#barcode", sku2);
			
					}

var barcode =  window.open('','BarcodeWindow','width=500,height=700');
			
   			var html = '<html><head><title>Barcode</title><style type="text/css">'+
   			'.page-break{display:block; page-break-before:always; }'+
			'.wrapper{margin-top:10px;font-size:20px;font-weight:bold;}'+
			'.fullSKU{float: left; font-size:20px;font-weight:bold;}'+
		   	'</style><svg id="barcode"></svg></head><body>'+second+'</body></html>';
   			barcode.document.open();
	    	barcode.document.write(html);
	    	barcode.document.close();

**Comment by lindell** [comment]
I'm sorry. But I don't get the problem and it seems to have something to do with the popup, and not the JsBarcode? I will close this issue, but if you think there is a bug in JsBarcode, feel free to re-open and provide more information on what the bug is.
