### ISSUE TITLE
extra spacing is showing below bar code

### ISSUE THREAD

**Issue by sred36** [lindell/JsBarcode#383]
![image](https://user-images.githubusercontent.com/35680138/129036850-d6caa6ee-7110-4818-a2a5-95bc63233bb6.png)

I have used below code to generate bar code . But some extra white space is  showing below bar code 

 jsBarcode('#crmMCIDBarcode', masterCRMID, {
            text: ' ',
            fontOptions: "bold",
            width: 0.55,
            height: 90,
            background: "#ffffff"
        });

**Comment by lindell** [comment]
Use `displayValue: false` to disable the printing of the text, which is causing the extra whitespace.
