### ISSUE TITLE
Any idea why these two barcodes slightly differ?   24 character ITF

### ISSUE THREAD

**Issue by visualjeff** [lindell/JsBarcode#386]
Any idea what the difference is between the two?  The upper one was printed by our register and the other was generated using jsBarcode.  We pad with a 0 and feed a 24 character transaction code into jsBarcode.  On the real barCode from the register we hide the leading zero.  So are customer doesn't see the padding.  Any idea???
    
![Screen Shot 2021-10-05 at 3 24 41 PM](https://user-images.githubusercontent.com/3446106/136112015-e80f6699-e012-4da8-bd16-765e78144af9.png)

Any insight would be appreciated.

Thank you!

Jeff

**Comment by visualjeff** [comment]
Any POS experts out there?

**Comment by lindell** [comment]
From what I can see, it seems that the register barcode is the same, it is just that the printing is not optimal. ITF bars are either 1 or 3 units in width. The left part of the red rectangle seems to not be a single width bar, and should therefore be the same.
