### ISSUE TITLE
Please help. JSBarcode script generates CODE-128 with correct pattern only from the last data.

### ISSUE THREAD

**Issue by mbovykin** [lindell/JsBarcode#387]
JSBarcode script generates CODE-128 with correct pattern only from the last data. I use text file for the data. For all data field it adds something to the end of generated barcode and only the last one is generated correctly. Please help
![bad](https://user-images.githubusercontent.com/92889545/139555454-27a30405-1aa1-4441-a770-4dc4c389f744.png)
![good](https://user-images.githubusercontent.com/92889545/139555455-bc31a3a3-f33b-40bc-a7cc-9552f692e0a1.png)

**Comment by lindell** [comment]
Could you please provide a way to reproduce this.

https://jsfiddle.net/6yf3rk1v/1/

**Comment by mbovykin** [comment]
I found the problem but don't know to fix it.  
1. When I type my data in text file I use Enter or Shift-Enter to create the next line. But this generate and extra code CRLF at the end of each line but not the last one. I was trying to use Notepad++ to remove them but I can do it with LF only, not CR.
2. Is any way when the script reads my text file to read the exact number of characters and eliminate those extra codes?

**Comment by mbovykin** [comment]
<?php



function get_file(){
    $my_arry = array();
    $file = fopen('bar.txt','r');
    while(!feof($file)) {

        array_push($my_arry,fgets($file));
      }
    fclose($file);
    
    return $my_arry;

}

function getBar(){
    $my_arr = get_file();
    unlink('bar.txt');
    $mybar = $my_arr[0];
    $file = fopen('bar.txt','w');
    for($z=0;$z < count($my_arr); $z++){
        if($z !== 0){
            $myline = strval($my_arr[$z]);
            fwrite($file,$myline);
        }
    
    }


    fclose($file);
    return $mybar;

}
?>

**Comment by mbovykin** [comment]
![image](https://user-images.githubusercontent.com/92889545/139589915-539c1504-9cb6-4ba4-9590-43677be895b5.png)

**Comment by lindell** [comment]
I hope you solve your problem, but it does not seem to be related to JsBarcode. Please reopen the issue if that is not the case.

**Comment by mbovykin** [comment]
No I didn't. Its related to text file that contains Return Carriage code after each line except the last one and I can't remove it. What could be a solution. I am not an expert with this.
