### ISSUE TITLE
Need EAN 8 Support

### ISSUE THREAD

**Issue by pivalig** [lindell/JsBarcode#39]
Hi, thank you for Great work!

It is possible to add a EAN 8 format support?

Thanks a lot.

**Comment by lindell** [comment]
Going to take a look at it soon

**Comment by pivalig** [comment]
Great, thank you!

**Comment by lindell** [comment]
Now added EAN8 support to the master branch. Going to make some tests before compiling it as a release but you can do it yourself if you want to use it now.

**Comment by pivalig** [comment]
Thanks a lot.

Will check tomorrow.

ср, 20 янв. 2016, 15:49, Johan Lindell <notifications@github.com>:

**Comment by lindell** [comment]
The EAN8 support is now in the [latest release](https://github.com/lindell/JsBarcode/releases/tag/1.6).
Also added it to [the generator](http://lindell.me/JsBarcode/)

**Comment by pivalig** [comment]
Awesome! 

We will use this feature here : http://provectapos.com

**Comment by lindell** [comment]
Nice :smile: always nice knowing where the code will be used :+1:
