### ISSUE TITLE
CODE128 Invalid Regular Expression Error

### ISSUE THREAD

**Issue by sercan-gundogdu** [lindell/JsBarcode#408]
Can't create CODE128 barcode

<img width="603" alt="Screen Shot 2022-04-13 at 01 27 28" src="https://user-images.githubusercontent.com/26443614/163065200-cded7239-5f35-46e2-9fbb-37edbccaacce.png">
<img width="603" alt="Screen Shot 2022-04-13 at 01 33 26" src="https://user-images.githubusercontent.com/26443614/163065620-e339ef7f-2d98-4898-8f9c-6c21110d4cb7.png">

<img width="714" alt="Screen Shot 2022-04-13 at 01 25 36" src="https://user-images.githubusercontent.com/26443614/163065323-8cef6513-1e41-44ba-86e2-cc935b4afe08.png">

**Comment by lindell** [comment]
Make sure UTF-8 is used for both the HTML file and the js file and it should work. 

https://github.com/lindell/JsBarcode/issues?q=invalid+range+in+character
