### ISSUE TITLE
Cannot scan long barcode in small paper size

### ISSUE THREAD

**Issue by khoabeotv** [lindell/JsBarcode#416]
I tried printing one barcode in two ways: jsBarcode on my website and the Bartender barcode application. I can't scan the barcode printed by jsBarcode, but I can san the other.

jsBarcode options:  `{width: 1}`
Print paper size: **35x35mm**

<img width="586" alt="Screen Shot 2022-08-17 at 19 32 30" src="https://user-images.githubusercontent.com/25880711/185125722-5f4b9f37-9dd5-4547-abee-67be989cf273.png">

**Comment by adomguo** [comment]
@khoabeotv hello。 do you solve this?
