### ISSUE TITLE
Jsbarcode misbehaving when removing chromium

### ISSUE THREAD

**Issue by benaichouchemm** [lindell/JsBarcode#419]
We are using jsbarcode 3.11.0 to generate barcode.
It happens that we had puppeteer, that required Chromium. We got rid of Puppeteer, thus Chromium, to our surprise the barcode that were generated had issue.

is there any dependencies on Chrome in jsbarcode?

Please we are using this in the backend and not in the Front End.

[barcode with issue](https://ibb.co/NT6jVqf)

**Comment by lindell** [comment]
There is most likely not a monospace font (or if you have defined another font) available where you are generating it now.
