### ISSUE TITLE
Uncaught TypeError: window[c.format] is not a function(…)

### ISSUE THREAD

**Issue by ljack** [lindell/JsBarcode#44]
No idea what's going on. It just doesn't work ;)

Uncaught TypeError: window[c.format] is not a function(…)

```
$("body").append("<img id='barcode'>");
[<body>​…​</body>​]
$("#barcode").JsBarcode("Hi!");
JsBarcode.all.min.js:19 Uncaught TypeError: window[c.format] is not a function(…)(anonymous function) @ JsBarcode.all.min.js:19JsBarcode @ JsBarcode.all.min.js:19f.fn.JsBarcode @ JsBarcode.all.min.js:21(anonymous function) @ VM1196:2InjectedScript._evaluateOn @ VM1159:875InjectedScript._evaluateAndWrap @ VM1159:808InjectedScript.evaluate @ VM1159:664
JsBarcode("#barcode","JsBarcode is easy!",{width:1,height:25});
JsBarcode.all.min.js:19 Uncaught TypeError: window[c.format] is not a function(…)(anonymous function) @ JsBarcode.all.min.js:19JsBarcode @ JsBarcode.all.min.js:19(anonymous function) @ VM1199:2InjectedScript._evaluateOn @ VM1159:875InjectedScript._evaluateAndWrap @ VM1159:808InjectedScript.evaluate @ VM1159:664
```

**Comment by lindell** [comment]
What browser are you using what version of JsBarcode? If you could include the entire html-page it would be of great help

**Comment by ljack** [comment]
Tried both 2.0-beta and 1.6.1. Browser is 
```
Version 48.0.2564.109 (64-bit)
Platform 7647.78.0 (Official Build) stable-channel panther
Firmware Google_Panther.4920.24.26
```

**Comment by lindell** [comment]
Google Panther? After some googling I assume you are running an chromebook with chromium. Is that right?

**Comment by ljack** [comment]
Yes,
 It's chromebox.
```
WebKit
537.36 (@0)
V8

4.8.271.19
User Agent

Mozilla/5.0 (X11; CrOS x86_64 7647.78.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36
Command Line

```

**Comment by ljack** [comment]
It's MeteorJs (and example meteorkitchen app which I'm extending) app I'm building located at https://laskuni-ljack1-1.c9users.io/ 
1) Register so you can log in
2) Goto Invoices
3) Add new invoice
4) Click Print to PDF
See console for error message.

**Comment by lindell** [comment]
I do also get the error so it seems like it occur because of the way meteor is loading javascript files. Going to take a look at this tomorrow and see if I can fix it

**Comment by ljack** [comment]
Ok, I was thinking that might a possible cause. I'll try different locations/ways to load the JsBarcode.js
There seems few options there ;) 
https://forums.meteor.com/t/what-is-the-best-way-to-add-an-external-javascript-file-external-api/2824/4

**Comment by ljack** [comment]
Seems like  $.getScript is working better.
```
e.g from meteor forum post
Meteor.startup(function(){
 $.getScript('https://conektaapi.s3.amazonaws.com/v0.3.2/js/conekta.js', function(){
  // script has loaded
  
 });
```

**Comment by lindell** [comment]
So it is working? :)

**Comment by ljack** [comment]
Yes. 
 Both the $.getScript and putting the JsBarcode.all.min.js in `client/compatibility/` works ;)

Doesn't work if the JsBarcode.js either in /client/lib/compatibility/, /client/lib/, /client/ etc.. Didn't test the client/compatibility/ before creating issue ;)

**Comment by lindell** [comment]
Great! Good luck with the rest of the project :)

**Comment by ljack** [comment]
Thank you! JsBarcode is awesome!
