### ISSUE TITLE
Nonprintable Characters

### ISSUE THREAD

**Issue by nlemberger** [lindell/JsBarcode#57]
Is there a way to add nonpritable characters to a barcode, such as a 'tab', 'newline', or 'carriage return'

**Comment by lindell** [comment]
Yes, CODE128 has support for them. Just use it like this:
````javascript
JsBarcode("#barcode", "Newline\n Tab\t CR\r");
````
[Here is a codepen showing it off](http://codepen.io/lindell/pen/dMRxvr)

**Comment by lindell** [comment]
Added some info to the wiki. Closing the issue.
https://github.com/lindell/JsBarcode/wiki/CODE128#non-printable-characters
