### ISSUE TITLE
Combining EAN13 + 2/5

### ISSUE THREAD

**Issue by jwrb** [lindell/JsBarcode#59]
Hello, do you have any plans to add EAN13 plus 5 and EAN13 plus 2 support to this package? Thanks

**Comment by lindell** [comment]
I want to add all barcodes that are used. So this i apparently one of them.

**Comment by lindell** [comment]
EAN-5 is now supported. It is not supported to include 13 and 5 in the same and that will probably take a while. I'm fixing EAN-2 soon.

**Comment by lindell** [comment]
EAN-2 is now also supported. 
Made som examples in a codepen: http://codepen.io/lindell/pen/QNMKdK

As I said before. Adding them together is probably going to be added, but not in the near future.

**Comment by jwrb** [comment]
Thank you very much for this! I tried implementing it myself but made an error... I was calculating my checksums incorrectly! My code was almost the same as yours!

**Comment by lindell** [comment]
I will soon put up the beta version of JsBarcode 3. It will support this the feature to combine barcodes. I replaced the api to be able to make more advanced customization.

````javascript
JsBarcode("#barcode")
  .EAN13("1234567890123")
  .blank(20)
  .EAN5("12345", {height: 85, textPosition: "top"})
  .draw();
````

![Barcode](http://i.imgur.com/CtPFc3r.png)

**Comment by lindell** [comment]
Combining barcodes is implemented in the new (beta) release. That together with [issue-60](https://github.com/lindell/JsBarcode/issues/59) can be seen in [this codepen example](http://codepen.io/lindell/pen/ZWogpM?editors=1010).
