### ISSUE TITLE
EAN Guard Bars

### ISSUE THREAD

**Issue by jwrb** [lindell/JsBarcode#60]
Hello,

Thank you for your additions of EAN5 and 2 addons for the EAN13 family.

Do you also have plans to support EAN guard bars. These are standard on a lot of EAN barcodes and also other families.

Thanks

**Comment by lindell** [comment]
Hi,

No problem with the EAN5 and 2, it used a lot of the standard EAN data so
it was not very hard to implement.

In regards to the guard bars, they are already there. But what you probably
mean is to make them taller as is the standard. Also to split the number in
three parts (first digit, group of 6 and group of 6).
I've had this in mind for a while but not had an plan for how to implement
it without losing the generality of the library as a whole. But I do now
have a solution in mind for it that would solve both the problem of making
the guard bars taller and the problem of adding two barcodes together.

//Johan

**Comment by lindell** [comment]
EAN guardbars is now implemented in the new (beta) release. That together with [issue-59](https://github.com/lindell/JsBarcode/issues/59) can be seen in [this codepen example](http://codepen.io/lindell/pen/ZWogpM?editors=1010).
