### ISSUE TITLE
Barcodes are blurry when printed from Chrome and other browsers

### ISSUE THREAD

**Issue by Jaded-Design** [lindell/JsBarcode#66]
Even the example page at: http://lindell.me/JsBarcode/ is producing a blurry barcode when you go to print from Chrome. 

IE is a little more crisp, but not by much.

**Comment by lindell** [comment]
@jwrb had the same problem. That's one one the reasons why SVG support is added for JsBarcode 3.

It does still have a beta tag but seems to be stable. [The only known bug](https://github.com/lindell/JsBarcode/issues/64) with it was patched 1 hour ago. I will create a new release with the changes as soon as possible.

Just use 
````
<svg id="barcode"></svg>
````

Instead of IMG or canvas and it should render much more nicely.

**Comment by lindell** [comment]
Just added the [new release](https://github.com/lindell/JsBarcode/releases/tag/v3.0.0-beta.3). Could you confirm this is solving the issue?

**Comment by Jaded-Design** [comment]
That fixed the blurriness issue completely.

Just a side note, the print preview shows the barcodes like this: 

![image](https://cloud.githubusercontent.com/assets/16841342/14681370/67d4e662-06e6-11e6-97d9-6901fb232ccc.png)

But once you print them, they do render correctly and you can scan them no problem. May just want to make a note about that so people are aware. 

Thanks a bunch for the quick solution. Great job.

**Comment by lindell** [comment]
This seems strange. Could you give the entire query you are using for the rendering and also what browser you are using?

**Comment by lindell** [comment]
And if you try to zoom in on the print preview. Is the problem gone?

**Comment by Jaded-Design** [comment]
Only browser not rendering print preview correctly, that I can see, is Chrome. I'm using version 49 (latest I believe)

Print preview renders correctly in Firefox, Safari, and Opera.

**Comment by Jaded-Design** [comment]
Zoom fixed it, it renders properly in print preview once you zoom in a bit. 

Thanks again for the assistance.

**Comment by lindell** [comment]
Perfect, then it's no problem but might be good to know as you said :smile:. Closing the issue.

**Comment by seksitha** [comment]
2020 still the rendering with `<img>` tag is blurry. my workaround is the set the `width` to 6 or 10. and then use CSS to scale down image for better quality. I use svg but the printing is suffer with my electron app. so `<img>`  is a go to for now.

**Comment by andreyrk** [comment]
> 2020 still the rendering with `<img>` tag is blurry. my workaround is the set the `width` to 6 or 10. and then use CSS to scale down image for better quality. I use svg but the printing is suffer in speed with my electron app. so `<img>` is a go to for now.

Add `image-rendering: nearest-neighbor; image-rendering: pixelated;` to the <img> CSS and the result is almost identical to SVG
