### ISSUE TITLE
I get ENOTFOUND for: bower info JsBarcode

### ISSUE THREAD

**Issue by romelgomez** [lindell/JsBarcode#67]
Hi, I have to use "JsBarcode": "jsbarcode#*", to get this dependence, if I use:  "JsBarcode": "3.0.1", i get ENOTFOUND. 

Kind regards

**Comment by lindell** [comment]
`bower install jsbarcode#3.0.1` works for me. Can you please give more information about how you are using it exactly.

**Comment by lindell** [comment]
The problem might be that you are using `JsBarcode` instead of `jsbarcode`

**Comment by lindell** [comment]
I did now register with capital letters as well so that might work.

**Comment by romelgomez** [comment]
Thanks, it works now.
