### ISSUE TITLE
Code39 control symbol support option

### ISSUE THREAD

**Issue by badlamer** [lindell/JsBarcode#69]
Support code39 control symbols

https://en.wikipedia.org/wiki/Code_39#Code_39_mod_43

**Comment by lindell** [comment]
I'll add this in the next few days.

**Comment by lindell** [comment]
Should the checksum be printed in the text below or not?

**Comment by lindell** [comment]
Seems like all other barcode generators I've been looking at is doing that. Doing the same.

**Comment by badlamer** [comment]
Yes, checksum will be printed

пн, 9 мая 2016, 17:46 Johan Lindell <notifications@github.com>:

**Comment by lindell** [comment]
Mod43 is now supported with the [v3.2.1](https://github.com/lindell/JsBarcode/releases/tag/v3.2.1) release.

**Comment by lindell** [comment]
[CodePen example](http://codepen.io/lindell/pen/grqBrq?editors=1010)

**Comment by lindell** [comment]
Added information about it to the [CODE39 page on the wiki](https://github.com/lindell/JsBarcode/wiki/CODE39#mod43-checksum).
