### ISSUE TITLE
ITF Support

### ISSUE THREAD

**Issue by andrelom** [lindell/JsBarcode#73]
I was checking the changes made in the latest version and noticed that the type ITF has been removed. According to the commit "dbb823609f5c5e3718ce69ea6af7cff1d7e233e2".

Is there any possibility of get ITF back?

**Comment by lindell** [comment]
Hi @andrelom.

I removed it since I thought it was not used (and only ITF-14 was used). But if there are people using it I will of course re-add it. Sorry about the removal.

**Comment by lindell** [comment]
Re(added the) support in [v3.3.5](https://github.com/lindell/JsBarcode/releases/tag/v3.3.5)

**Comment by andrelom** [comment]
Hi @lindell.

I'm realy glad with your help and attention.
Here in Brazil, the majorit of banks uses the ITF to generate barcodes, because them follow the "FEBRABAN" specification.

Thanks!
