### ISSUE TITLE
/bin on IIS server

### ISSUE THREAD

**Issue by fabriciocs** [lindell/JsBarcode#74]
I have an error on IIS server because the /bin in the path of jsbarcode.

here you can see an explanation [http://goo.gl/91e4iu](http://goo.gl/91e4iu)

Can you consider change this folder name? maybe change for build.

**Comment by fschaeffer** [comment]
or as in most distributions (see https://github.com/twbs/bootstrap, https://github.com/jquery/jquery, https://github.com/vakata/jstree, https://github.com/select2/select2, https://github.com/selectize/selectize.js) the folder containing minified and concatenated build artifacts is called **dist** containing subfolders for css / js / img / fonts

So the final folder layout would be
```
JsBarcode
  bin
    node
  dist
    js
      JsBarcode.all.min.js
  src
```

**Comment by lindell** [comment]
I was thinking about renaming the folder any way since `bin` stands for binary and that not really what the folder contains. @fschaeffer isn't this just used when the library actually contains css / img / js. Look for example at [jQuery](https://github.com/jquery/jquery) that you linked. They do not use the `dist` name but instead `build` (and they only have javascript files in the directory). Not really sure about this but makes a bit of sense at least.

**Comment by lindell** [comment]
But the question then becomes where to put the node files

**Comment by fschaeffer** [comment]
@lindell you're right, I only searched the other distros where js and css are provided and they use the subfolder structure.

IMO ```build``` should contain files which are necessary to build a project (less / sass files and so on) whereas ```dist``` contains the result of a build (and minify) process...

As you're only providing JS files ```build``` would be a good start, though I still prefer ```dist```, as it easier to get your head around when using a new lib .... anyway, ```build``` would also be fine

**Comment by lindell** [comment]
Was looking a bit more and `dist` seems to be the right way to do it. Do you still think it should be under `dist/js` even if there is not other output from the build process than javascript files?

**Comment by fschaeffer** [comment]
For the time being I think they could be located under ```dist``` directly (as in e.g. JsTree), but who knows, maybe at some time additional files (like themes, locales or map.files) will be added so why not just start by embracing the "standard" way other libraries use ...

**Comment by lindell** [comment]
The new structure is now pushed. I wait for a [jsdelivr pull request](https://github.com/jsdelivr/jsdelivr/pull/11685) to merge before pushing the release.

**Comment by lindell** [comment]
New release pushed (v.3.3.6) with the new structure.
