### ISSUE TITLE
Export to jQuery part fails if $ is encapsulated / $ does not refer to jQuery

### ISSUE THREAD

**Issue by leeder** [lindell/JsBarcode#75]
I'm trying to use the JsBarcode lib within a project where the $ is encapsulated so it is not available in the global scope, therefore when trying to create a barcode, the lib fails on the line 882.
```javascript
// Export to jQuery
	if (typeof jQuery !== 'undefined') {
		jQuery.fn.JsBarcode = function (content, options) {
			var elementArray = [];
			$(this).each(function () {
				elementArray.push(this);
			});
			return JsBarcode(elementArray, content, options);
		};
	}
```
After changing $(this) to jQuery(this) everything works fine.

**Comment by lindell** [comment]
Could you give some more detail of how you do the encapsulation and how I could reproduce it?

**Comment by lindell** [comment]
Oh, did read this again. Do you mean that this fixes the problem?

````javascript
// Export to jQuery
    if (typeof jQuery !== 'undefined') {
        jQuery.fn.JsBarcode = function (content, options) {
            var elementArray = [];
            jQuery(this).each(function () {
                elementArray.push(this);
            });
            return JsBarcode(elementArray, content, options);
        };
    }
````

**Comment by lindell** [comment]
Did just that in https://github.com/lindell/JsBarcode/commit/1a4d532509fe71a69ad6119119027fba28dc949a .

**Comment by lindell** [comment]
Did also push a new release with this change (v.3.3.6). Let me know if this fixes the problem :smile:

**Comment by leeder** [comment]
Thanks for the update, it has fixed the issue.
