### ISSUE TITLE
Can the barcode be rotate?

### ISSUE THREAD

**Issue by mihai-craita** [lindell/JsBarcode#80]
Is there an easy way to rotate the barcode by 90deg or 270 deg?

Thanks!

**Comment by lindell** [comment]
The library itself does not support it.

That said. It would be easy to do with some basic CSS.

http://codepen.io/lindell/pen/EyvEVQ

Is that what you are looking for?

**Comment by mihai-craita** [comment]
Hey Johan, thanks for your prompt reply, yes this is how I'm doing it right now (using css). 
I thought there is a way to do it using the library, that I somehow missed it in the docs.

Thanks for the great library, keep up the good work!

**Comment by germanger** [comment]
The CSS solution doesn't work for me because I'm converting the canvas to a JPG using HTML5 blobs:

        // Create barcode
        JsBarcode("#barcode", "hello");
        
        // Obtain canvas
        var barcodeCanvas = document.getElementById("barcode");
        
        // Rotate
       barcodeCanvas.getContext("2d").rotate(90 * Math.PI/180);
        
       // Convert to JPG in a URL
       var jpegURL = barcodeCanvas.toDataURL("image/jpeg");


I'm accessing to jpegURL but the barcode is not rotated....

Any help on rotating the canvas containing the barcode?

Here is a plunkr:
https://plnkr.co/edit/BUB83NzthxQTHKhABZ0L?p=preview

**Comment by lindell** [comment]
The plnkr you are linking are working for me. Did you fix it?

**Comment by germanger** [comment]
Yes!

**Comment by lwestfall** [comment]
I wonder if the decision against adding a rotation option could be reconsidered. Rotation using css can be problematic especially in cases where the resulting svg is not close to square as the flow of content doesn't change with transformation. In other words, the width and height don't rotate and this can cause surrounding elements not to flow as desired. It takes a lot of tweaking margins/padding/transform-origin etc. to make everything fit, but if the width of the barcode is changed you have to do it all over again. Very frustrating!

I forked the codepen above to illustrate the problem. Notice how barcode 1 overflows off the top and also draws on top of the other content.
https://codepen.io/luuuuuke/pen/GROwWLL

Thanks!

**Comment by baltamar3** [comment]
> Yes!

How could I totate it to the other side?
