### ISSUE TITLE
Arabic Support 

### ISSUE THREAD

**Issue by mhbu50** [lindell/JsBarcode#82]
Could you add Arabic letter characters Support ?

**Comment by lindell** [comment]
> Barcodes (as in: 1D) can only contain the characters specified in their specification. For example, EAN13 can only hold numbers, Code128 can contain numbers, US-ASCII letters and some special characters, etc.

> If you are talking about 1D-Barcodes, look into their definition. I know of no 1D-barcode that can hold unicode (specifically arabic) letters.

http://stackoverflow.com/a/35427835

You might want to look into printing your data on a 2D barcode such as a QR-code.

**Comment by mhbu50** [comment]
it is working only with Format: GenericBarcode:
![image](https://cloud.githubusercontent.com/assets/11526423/16894546/42235924-4b62-11e6-904b-9ebc830f05d5.png)

**Comment by lindell** [comment]
Generic Barcode is just that. A generic barcode that always generates the sequence `10101010...10101`. It accepts everything but does not encode it.

**Comment by lindell** [comment]
If you have an barcode symbology that can encode Arabic characters, please link me to it and I'll see what I can do. But when searching for it I can't find any symbologies that support utf-8 so I think you are out of luck :unamused:

**Comment by lindell** [comment]
Have your question been answered? And can the issue be closed?
