### ISSUE TITLE
how to create isbn(ean-13 based) barcode using JsBarcode?

### ISSUE THREAD

**Issue by Tony1952466760** [lindell/JsBarcode#85]
I want to create isbn barcode, can you tell me?

**Comment by lindell** [comment]
You answered the question in the title. ISBN numbers are always EAN-13 numbers.

Just do this for ISBN=9783161484100
`````javascript
JsBarcode("#barcode", "9783161484100", {
  format: "EAN13",
  textMargin: 0
});
````

http://codepen.io/lindell/pen/oLqVbb

**Comment by lindell** [comment]
Is there something more you are wondering about? Otherwise I will close the issue
