### ISSUE TITLE
Can't install with NPM

### ISSUE THREAD

**Issue by gharley** [lindell/JsBarcode#86]
fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory
occurs multiple times.

**Comment by lindell** [comment]
First of all. Could you please give information on what kind of machine you are trying to install on.

Second, I assume you looked at the installation instructions for node-canvas https://github.com/Automattic/node-canvas. If not, do that.

**Comment by lindell** [comment]
I now removed the `node-canvas` package from dependencies and moved it to devDependencies. If you are using JsBarcode in node.js you still need it. But if it is for webdev you should not have the problem any more

**Comment by gharley** [comment]
I am installing on Windows and yes, I apparently missed part of the install steps.  I ended up just 'require'ing JsBarcode.all.min.js which I like better because I can generate into an svg tag and don't need a canvas.  It works beautifully, thank you for your work!
