### ISSUE TITLE
SVG strings

### ISSUE THREAD

**Issue by stephen-last** [lindell/JsBarcode#89]
I'd like to use JsBarcode to generate SVG strings for use with [PDFKit - SVG paths](http://pdfkit.org/docs/vector.html#svg_paths).

Are there any methods to return an SVG string..?

**Comment by lindell** [comment]
What do you mean when you say
> SVG string

And are you using this on the web or in node?

**Comment by stephen-last** [comment]
Node. Like this: http://pdfkit.org/docs/vector.html#svg_paths

**Comment by lindell** [comment]
So what you are asking is if JsBarcode will be able to generate javascript code that will use the PDFKit library so that you will be able to draw the barcode with that?

In that case it is not supported.

**Comment by stephen-last** [comment]
Thank you!

**Comment by enyachoke** [comment]
@stephen-last  I had the same problem I used https://github.com/froatsnook/bardcode instead and adapted https://github.com/mailzwj/sstp to return a path string. https://github.com/enyachoke/svg_path_bardcode/blob/master/test.js hope this helps.

**Comment by stephen-last** [comment]
@enyachoke Thanks for that! I created something myself and published it: https://github.com/stephen-last/srtps / https://www.npmjs.com/package/srtps.

I used [bardcode](https://github.com/froatsnook/bardcode) to generate the svg string, then my [srtps](https://github.com/stephen-last/srtps) to grab the 'rects' and build an svg path string. Works well with [pdfkit](https://github.com/devongovett/pdfkit) and the `.path()` method.
