### ISSUE TITLE
JsBarcode not working in IE 

### ISSUE THREAD

**Issue by lornyia** [lindell/JsBarcode#90]
The barcode works fine in chrome, but I'm have an issue with the error "the value of the property 'JsBarcode' is null or undefined, not a Function object" in IE.

**Comment by lindell** [comment]
All use cases I test right now is working as they should in IE.

Could you provide all code you are using to get this error? HTML and JavaScript

**Comment by lindell** [comment]
For example. The [Simple CodePen Demo](http://codepen.io/lindell/pen/eZKBdO?editors=1010) is working.

![IE](http://i.imgur.com/ygEOu6z.png)

**Comment by lornyia** [comment]
Resolved.

**Comment by lindell** [comment]
What was the problem? :smile:

**Comment by lornyia** [comment]
IE was setting back to default (IE 7) which is not compatible with JsBarcode.
