### ISSUE TITLE
CODE128 refactoring

### ISSUE THREAD

**Issue by lindell** [lindell/JsBarcode#92]
CODE128 is a bit of a mess right now. Some refactoring is needed.

**Comment by SanichKotikov** [comment]
I suppose I can try, if I have some time and if you don't mind :) Any issues I have to know before?

**Comment by lindell** [comment]
I was thinking this issue as a reminder for myself, but if you would like to do it I would love it 😄 I don't thing there is something special you need to know before you get started.

**Comment by SanichKotikov** [comment]
I have been looking into the issue and already updated the path that responds to auto selecting of mode. @lindell can you look at this before I go to rewrite the CODE128 class? https://github.com/SanichKotikov/JsBarcode/commit/54886a3906ebacf10241a4304c41862ac53164ea

**Comment by lindell** [comment]
It looks good so far. Altho some part really need comments, I still don't see a lot of this code as self explanatory unfortunately (because it is probably impossible to do).

The `bin` folder is used so that older versions of node can be supported and still use newer ECMAscript syntax. The `dist` folder is so that people that use the library the "old fashioned" way by taking these files and put them directly into a `<script>`-tag. The `dist` folder is also used by some CDNs, mainly jsdelivr.
But the bin and dist folder should never manually be commited, I have some automation to do that every new release :)

**Comment by SanichKotikov** [comment]
Yep, I spent some time before I realised what happen in the code. I'll try to add some comments then.

> But the bin and dist folder should never manually be commited

Hmm, so we don't need to commit and we can't add them into `.gitignore`. Right?

**Comment by lindell** [comment]
Yea, it's a bit annoying that you can't add them to `.gitignore`. I would absolutely do if I could
