### ISSUE TITLE
can we display different value on text than barcode value

### ISSUE THREAD

**Issue by safarigps** [lindell/JsBarcode#94]
We have a requirement to  hide some part of text, while displaying bar code text, just wondering, is it possible?

**Comment by lindell** [comment]
It is not possible in the current version but this is definitely something that should be added. This might not work with EAN-13 and UPC but should be a pretty easy add for the rest. Which symobology do you intend to use this with?

**Comment by lindell** [comment]
[This should fix the problem](https://gist.githubusercontent.com/lindell/68fbfdf5caec2d73c0e4d868e9aec6fd/raw/c63f178937613cf6dcc68c01e2890027e999f43e/JsBarcode.all.min.js) for everything except EAN / UPC. I will wait with a release until I know how to to with the special symbologies.

**Comment by safarigps** [comment]
How can we do it on code39?

On Tue, Aug 9, 2016, 8:28 AM Johan Lindell <notifications@github.com> wrote:

>

> It is not possible in the current version but this is definitely
something that should be added. This might not work with EAN-13 and UPC but
should be a pretty easy add for the rest. Which symobology do you intend to
use this with?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
<https://github.com/lindell/JsBarcode/issues/94#issuecomment-238537571>, or
mute the thread

**Comment by lindell** [comment]
Use the code linked above (for all barcodes) or [this one](https://gist.githubusercontent.com/lindell/1fa73de1f9aa113982feef4e67396a23/raw/76351fbfba66263d56107d8a1b35d5c23acce366/JsBarcode.code39.min.js) for just CODE39.

Then use the option `text` to overide with what you like.

````javascript
JsBarcode("#barcode", "Hello", {
	format: "CODE39",
	text: "hi"
});
````

![](http://i.imgur.com/69qyUJx.png)

**Comment by safarigps** [comment]
Thank you:), you are the best.

**Comment by LenhartHuang** [comment]
Oh my god! Your code really helped me a lot. I'm so appreciate it for your help.
