### ISSUE TITLE
Cannot scan after printing

### ISSUE THREAD

**Issue by Scheder** [lindell/JsBarcode#95]
Hey Lindell,

First off, great library. I upgraded to the latest JsBarcode and am using svg to my big delight. I can create and scan (with my phone) perfectly on my computer screen, but when i print out the barcode, somehow the lines become thicker. When I check the html, it clearly shows that as many pixels are used for the white space as the black space, but after printing, there seems to be less whitespace... :(

**Comment by lindell** [comment]
Hi, it seems like the problem lies in some sort of scaling with the printing. Could you try to get as good of a picture of the printed barcode as you could and post it here? And also provide the settings and data you are using for the barcode?

**Comment by Scheder** [comment]
I added 3 pictures labelled '1', '2', and '7' (the number is within the pic). 1 was when still using "img". Picture is clear-ish, but text was rubbish. 2 was when using svg. Much better text, but lines became thicker. 7 was with BarWidth set to 2. More white space, but still not the correct ratio.

The printer is a Brother QL-570 label printer. I'm using chrome (as firefox crashed when trying to print... so could not really test on firefox). The printer settings are "Landscape", "1-1/7'' x 3-1/2''", no margins. The data used is "JsBarcode(imgID, barValue, {format:"EAN13", displayValue:true, fontSize:20, width:2, height:60});" with barValue a regular EAN13 number. In this case "0000000220736", "0000000220736" and "0000000004480".

![Img3](https://cloud.githubusercontent.com/assets/10059706/17517433/b8dfc8a6-5e43-11e6-82ab-acfb3f810b6c.jpg)
![Img2](https://cloud.githubusercontent.com/assets/10059706/17517434/b8dfd5bc-5e43-11e6-8152-9e75ad097895.jpg)
![Img1](https://cloud.githubusercontent.com/assets/10059706/17517432/b8df44f8-5e43-11e6-8536-0b1268162886.jpg)

**Comment by lindell** [comment]
The problem seems to be (as you said) that the printer makes the lines bigger. (Maybe printing correctly and the ink then flowing out?). The images that JsBarcode generates should be correct. What could be done is maybe if an option is added. This is unfortunatety not something I'm going to add but would gladly accept a Pull Request if you like to do it.

An ugly solution would be to do the change directly in [this function](https://github.com/lindell/JsBarcode/blob/master/src/renderers/svg.js#L158)


````javascript
function drawLine(x, y, width, height, parent){
	var ratio = 0.8;

	var line = document.createElementNS(svgns, 'rect');

	line.setAttribute("x", x + (1 - ratio) * width / 2);
	line.setAttribute("y", y);
	line.setAttribute("width", width * ratio);
	line.setAttribute("height", height);

	parent.appendChild(line);
}
````

Try to change the ratio and see if it fixes the problem.

**Comment by lindell** [comment]
Or try to use [this script](https://gist.githubusercontent.com/lindell/c4610639d4e5118baf4c0297a7c9c9e4/raw/50004ce1c5818255b62b514c76073e7813e36865/JsBarcode.all.min.js). Use the options `ratio` and set it to something like `0.8`.

**Comment by Scheder** [comment]
You're a lifesaver! It scans pretty quickly on both the computer as on the printed version!

Thanks for your quick fix!

**Comment by lindell** [comment]
Nice that the issue was solved. May I ask what you are printing and how it's going to be used? Motivates me to know what people are using the library for :smile:

**Comment by Scheder** [comment]
Actually I'm using someone else's library which is a wrapper on yours, but it has not been updated regularly, so I made my own changes, like updating to your latest version etc.

That library can be found here: https://share.servicenow.com/app.do#/detailV2/c869e5122b61f500bddaff70f8da1595/overview

You know how many companies have labels on their assets (eg: screens, laptops, etc)? Ours wants barcodes instead, as they are easier to work with. So we are basically using that library (and thus yours) to tag our assets ;) The plugin has been downloaded 141 times so far, so who knows where your code is being used atm.

**Comment by lindell** [comment]
Had no idea that it existed but always nice when it can be implemented in ways that will make more people using it.

Thanks for sharing your usecase :smile:

**Comment by ravikant31** [comment]
Thanks for the library, but unfortunately non of the fixes are working me. I am unable to scan the barcode in PC as well as printout.

**Comment by lindell** [comment]
@ravikant31 If you want any assistance you would have to create a new issue detailing how you generate the barcode and other information of why it does not generate correct barcodes.
