### ISSUE TITLE
Callback Function?

### ISSUE THREAD

**Issue by jdarmst** [lindell/JsBarcode#98]
Is there way to do a .done(function(){ something }); or to queue generation? I have a page that generates a variable amount of barcodes on load, and if I don't set a timer in between, some don't generate. I can create an example if requested.

**Comment by lindell** [comment]
JsBarcode is not synchronous which makes such a function effectively worthless.

But it does actually exist in the form of the `valid` option. 

````javascript
JsBarcode("#barcode", "test", {
  valid: function(){ something }
});
````
But as said. There is no reason to do this since this gives the exact same result.

````javascript
JsBarcode("#barcode", "test");
something
````

**Comment by lindell** [comment]
So what you probably want to do is.

http://codepen.io/lindell/pen/wWVVAP

**Comment by lindell** [comment]
Something still unclear? I will close the issue otherwise

**Comment by jdarmst** [comment]
Sorry, busy with life. I just set a timer on generation. You can see it in use at https://vorisi.com/barcodes
If you save some barcodes, you get a hash at the end of the url. If you reload that page, you'll see that barcodes populate.

**Comment by lindell** [comment]
Nice you got it to work but as I said it should be unnecessary to do so.

What I'm wondering is why you are using a super old version of the barcode (relativly). I would guess the version you are using is older than a year old.

**Comment by garygreen** [comment]
@lindell I have a similar use case, isn't your `setTimeout` solution a bit hacky? Isn't there anyway you could add a asynchronous callback to the render function?

```javascript
JsBarcode("#barcode")
  .options({font: "OCR-B"}) // Will affect all barcodes
  .EAN13("1234567890128", {fontSize: 18, textMargin: 0})
  .blank(20) // Create space between the barcodes
  .EAN5("12345", {height: 85, textPosition: "top", fontSize: 16, marginTop: 15})
  .render(function() {
      alert('yee!');
  }));
```

**Comment by lindell** [comment]
@garygreen The only reason I showed the timeout is because @jdarmst asked about it in the original post. 

As stated already, JsBarcode renders synchronously, so if you just loop all the barcodes and render them, code after that will not execute before the barcodes have rendered.

**Comment by garygreen** [comment]
Apologies, I misread your original post. Would this be the same case with multiple `<svg>` with the options on the tags and using the below?

```javascript
JsBarcode(".barcode").init();
console.log('all .barcodes are fully rendered ready for printing!');
```

**Comment by lindell** [comment]
It is the same :)
